#ifndef CONFIGSTORAGE_H
#define CONFIGSTORAGE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;

/* Function prototypes */
bool ConfigStorage_loadConfig(const AppConfig* config);
bool ConfigStorage_saveConfig(const AppConfig* config);
bool ConfigStorage_validateConfig(const AppConfig* config);
void ConfigStorage_loadDefaults(AppConfig* config);

#ifdef __cplusplus
}
#endif

#endif /* CONFIGSTORAGE_H */
