/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Domain/SensorProcessor/SensorProcessor.h"

// Sensor processing logic
// Reads from hardware managers and updates AppData
#include <Arduino.h>
#include "AppConfig.h"
#include "Data/ADS1115Manager/ADS1115Manager.h"
#include "Data/MAX31856Manager/MAX31856Manager.h"
#include "Data/BME280Manager/BME280Manager.h"
#include <Display/SensorConvert.h>
#include <Display/HardwareMap.h>
#include <Display/AppData.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: SensorProcessor */
static AppConfig SensorProcessor_config = {};

void SensorProcessor_initialize(const AppConfig* cfg) {
    SensorProcessor_config = (*cfg);
}

static float SensorProcessor_getAtmosphericPressurekPa(const AppData* appData) {
    if (appData->absoluteBarometricpressurekPa > 0.0) {
        return appData->absoluteBarometricpressurekPa;
    }
    return SensorConvert_defaultAtmosphericPressure();
}

static void SensorProcessor_updateAppDataForSpn(AppData* appData, uint16_t spn, float value) {
    switch (spn) {
        case 175: {
            appData->oilTemperatureC = value;
            break;
        }
        case 110: {
            appData->coolantTemperatureC = value;
            break;
        }
        case 1637: {
            appData->coolantTemperatureC = value;
            break;
        }
        case 174: {
            appData->fuelTemperatureC = value;
            break;
        }
        case 105: {
            appData->boostTemperatureC = value;
            break;
        }
        case 1363: {
            appData->boostTemperatureC = value;
            break;
        }
        case 1131: {
            appData->cacInletTemperatureC = value;
            break;
        }
        case 1132: {
            appData->transferPipeTemperatureC = value;
            break;
        }
        case 1133: {
            appData->airInletTemperatureC = value;
            break;
        }
        case 172: {
            appData->airInletTemperatureC = value;
            break;
        }
        case 441: {
            appData->engineBayTemperatureC = value;
            break;
        }
        case 100: {
            appData->oilPressurekPa = value;
            break;
        }
        case 109: {
            appData->coolantPressurekPa = value;
            break;
        }
        case 94: {
            appData->fuelPressurekPa = value;
            break;
        }
        case 102: {
            appData->boostPressurekPa = value;
            break;
        }
        case 106: {
            appData->airInletPressurekPa = value;
            break;
        }
        case 1127: {
            appData->cacInletPressurekPa = value;
            break;
        }
        case 1128: {
            appData->transferPipePressurekPa = value;
            break;
        }
        default: {
            break;
        }
    }
}

static void SensorProcessor_processTempInputs(AppData* appData) {
    for (uint8_t i = 0; i < TEMP_INPUT_COUNT; i += 1) {
        uint16_t assignedSpn = SensorProcessor_config.tempInputs[i].assignedSpn;
        if (assignedSpn == 0) {
            continue;
        }
        uint8_t device = HardwareMap_tempDevice(i);
        uint8_t channel = HardwareMap_tempChannel(i);
        float voltage = ADS1115Manager::getVoltage(device, channel);
        float tempC = SensorConvert_ntcTemperature(voltage, &SensorProcessor_config.tempInputs[i]);
        SensorProcessor_updateAppDataForSpn(appData, assignedSpn, tempC);
    }
}

static void SensorProcessor_processPressureInputs(AppData* appData) {
    for (uint8_t i = 0; i < PRESSURE_INPUT_COUNT; i += 1) {
        uint16_t assignedSpn = SensorProcessor_config.pressureInputs[i].assignedSpn;
        if (assignedSpn == 0) {
            continue;
        }
        uint8_t device = HardwareMap_pressureDevice(i);
        uint8_t channel = HardwareMap_pressureChannel(i);
        float voltage = ADS1115Manager::getVoltage(device, channel);
        float pressurekPa = SensorConvert_pressure(voltage, &SensorProcessor_config.pressureInputs[i], SensorProcessor_getAtmosphericPressurekPa(appData));
        SensorProcessor_updateAppDataForSpn(appData, assignedSpn, pressurekPa);
    }
}

static void SensorProcessor_processEgt(AppData* appData) {
    bool egtReady = MAX31856Manager::isEnabled();
    if (SensorProcessor_config.egtEnabled && egtReady) {
        appData->egtTemperatureC = MAX31856Manager::getTemperatureC();
    }
}

static void SensorProcessor_processBme280(AppData* appData) {
    bool bmeReady = BME280Manager::isEnabled();
    if (SensorProcessor_config.bme280Enabled && bmeReady) {
        appData->ambientTemperatureC = BME280Manager::getTemperatureC();
        appData->humidity = BME280Manager::getHumidity();
        appData->absoluteBarometricpressurekPa = BME280Manager::getPressurekPa();
    }
}

void SensorProcessor_processAllInputs(AppData* appData) {
    SensorProcessor_processTempInputs(appData);
    SensorProcessor_processPressureInputs(appData);
    SensorProcessor_processEgt(appData);
    SensorProcessor_processBme280(appData);
}
