/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Hardware.h"

// Hardware initialization
// Single entry point for all sensor hardware setup.
// Called from setup() and after any config change.
#include <AppConfig.h>
#include <Data/ADS1115Manager.h>
#include <Data/MAX31856Manager.h>
#include <Data/BME280Manager.h>
#include <Data/SensorValues.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: Hardware */

static bool Hardware_isValueAssigned(const AppConfig& config, EValueId id) {
    for (uint8_t i = 0; i < TEMP_INPUT_COUNT; i += 1) {
        if (config.tempInputs[i].assignedValue == id) {
            return true;
        }
    }
    for (uint8_t i = 0; i < PRESSURE_INPUT_COUNT; i += 1) {
        if (config.pressureInputs[i].assignedValue == id) {
            return true;
        }
    }
    if (id == EValueId_TURBO1_TURB_INLET_TEMP) {
        return config.egtEnabled;
    }
    if (id == EValueId_AMBIENT_PRES) {
        return config.bme280Enabled;
    }
    if (id == EValueId_AMBIENT_TEMP) {
        return config.bme280Enabled;
    }
    if (id == EValueId_AMBIENT_HUMIDITY) {
        return config.bme280Enabled;
    }
    return false;
}

static void Hardware_populateHardwareFlags(const AppConfig& config) {
    for (uint8_t i = 0; i < EValueId_VALUE_ID_COUNT; i += 1) {
        EValueId id = static_cast<EValueId>(i);
        bool has = Hardware_isValueAssigned(config, id);
        SensorValues_current[id].hasHardware = has;
    }
}

void Hardware_initialize(const AppConfig& config) {
    Hardware_populateHardwareFlags(config);
    ADS1115Manager_initialize(config);
    MAX31856Manager_initialize(config);
    BME280Manager_initialize(config);
}
