/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Domain/ossm.h"

// Main OSSM application logic
// Handles sensor polling, J1939 messaging, and command processing
#include <Arduino.h>
#include <Display/AppData.h>
#include <AppConfig.h>
#include "Data/ConfigStorage/ConfigStorage.h"
#include "Data/ADS1115Manager/ADS1115Manager.h"
#include "Data/MAX31856Manager/MAX31856Manager.h"
#include "Data/BME280Manager/BME280Manager.h"
#include "Domain/SensorProcessor/SensorProcessor.h"
#include "Domain/CommandHandler/CommandHandler.h"
#include <Display/J1939Bus.h>
#include "Interface/SerialCommandHandler/SerialCommandHandler.h"

#include <stdbool.h>

/* Scope: Ossm */
static AppData Ossm_appData = {0};
static AppConfig Ossm_appConfig = {};
static IntervalTimer Ossm_sensorTimer = {};
static bool Ossm_sensorUpdateReady = false;
static elapsedMillis Ossm_halfSecondMillis = {};
static elapsedMillis Ossm_oneSecondMillis = {};

void Ossm_sensorTimerCallback(void) {
    Ossm_sensorUpdateReady = true;
}

void Ossm_processSensorUpdates(void) {
    ADS1115Manager::update();
    MAX31856Manager::update();
    BME280Manager::update();
    SensorProcessor::processAllInputs();
}

void Ossm_sendJ1939Messages(void) {
    if (Ossm_halfSecondMillis >= 500) {
        J1939Bus_sendPgn65270(Ossm_appData.airInletPressurekPa, Ossm_appData.airInletTemperatureC, Ossm_appData.egtTemperatureC, Ossm_appData.boostPressurekPa);
        J1939Bus_sendPgn65263(Ossm_appData.fuelPressurekPa, Ossm_appData.oilPressurekPa, Ossm_appData.coolantPressurekPa);
        J1939Bus_sendPgn65190(Ossm_appData.boostPressurekPa, Ossm_appData.cacInletPressurekPa);
        Ossm_halfSecondMillis = 0;
    }
    if (Ossm_oneSecondMillis >= 1000) {
        J1939Bus_sendPgn65269(Ossm_appData.ambientTemperatureC, Ossm_appData.airInletTemperatureC, Ossm_appData.absoluteBarometricpressurekPa);
        J1939Bus_sendPgn65262(Ossm_appData.coolantTemperatureC, Ossm_appData.fuelTemperatureC, Ossm_appData.oilTemperatureC);
        J1939Bus_sendPgn65129(Ossm_appData.boostTemperatureC, Ossm_appData.coolantTemperatureC);
        J1939Bus_sendPgn65189(Ossm_appData.cacInletTemperatureC, Ossm_appData.transferPipeTemperatureC, Ossm_appData.engineBayTemperatureC);
        J1939Bus_sendPgn65164();
        Ossm_oneSecondMillis = 0;
    }
}

void Ossm_setup(void) {
    Serial.begin(115200);
    Serial.println("OSSM Initializing...");
    if (!ConfigStorage::loadConfig(&Ossm_appConfig)) {
        Serial.println("Loading default configuration");
        ConfigStorage::loadDefaults(&Ossm_appConfig);
        ConfigStorage::saveConfig(&Ossm_appConfig);
    } else {
        Serial.println("Configuration loaded from EEPROM");
    }
    ADS1115Manager::initialize(&Ossm_appConfig);
    MAX31856Manager::initialize(&Ossm_appConfig);
    BME280Manager::initialize(&Ossm_appConfig);
    SensorProcessor::initialize(&Ossm_appConfig, &Ossm_appData);
    CommandHandler::initialize(&Ossm_appConfig, &Ossm_appData);
    J1939Bus_initialize(&Ossm_appData, &Ossm_appConfig);
    SerialCommandHandler::initialize(&Ossm_appConfig, &Ossm_appData);
    Ossm_sensorTimer.begin(Ossm_sensorTimerCallback, 50000);
    Serial.println("OSSM Ready");
}

void Ossm_loop(void) {
    if (Ossm_sensorUpdateReady) {
        Ossm_processSensorUpdates();
        Ossm_sensorUpdateReady = false;
    }
    SerialCommandHandler::update();
    Ossm_sendJ1939Messages();
}
