/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "ossm.h"

// Main OSSM application logic
// Handles sensor polling, J1939 messaging, and command processing
#include <Arduino.h>
#include <Display/AppData.h>
#include <AppConfig.h>
#include "../Data/ConfigStorage.h"
#include "../Data/ADS1115Manager.h"
#include "../Data/MAX31856Manager.h"
#include "../Data/BME280Manager.h"
#include "SensorProcessor.h"
#include "CommandHandler.h"
#include <Display/J1939Bus.h>
#include "SerialCommandHandler.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: Ossm */
static AppData Ossm_appData = {0};
static AppConfig Ossm_appConfig = {0};
static IntervalTimer Ossm_sensorTimer = {};
static bool Ossm_sensorUpdateReady = false;
static elapsedMillis Ossm_halfSecondMillis = {};
static elapsedMillis Ossm_oneSecondMillis = {};

void Ossm_sensorTimerCallback(void) {
    Ossm_sensorUpdateReady = true;
}

void Ossm_processSensorUpdates(void) {
    ADS1115Manager_update();
    MAX31856Manager_update();
    BME280Manager_update();
    SensorProcessor_processAllInputs(Ossm_appData);
}

void Ossm_sendJ1939Messages(void) {
    if (Ossm_halfSecondMillis >= 500) {
        J1939Bus_sendPgn65270(Ossm_appData.airInletPressurekPa, Ossm_appData.airInletTemperatureC, Ossm_appData.egtTemperatureC, Ossm_appData.boostPressurekPa);
        J1939Bus_sendPgn65263(Ossm_appData.fuelPressurekPa, Ossm_appData.oilPressurekPa, Ossm_appData.coolantPressurekPa);
        J1939Bus_sendPgn65190(Ossm_appData.boostPressurekPa, Ossm_appData.cacInletPressurekPa);
        Ossm_halfSecondMillis = 0;
    }
    if (Ossm_oneSecondMillis >= 1000) {
        J1939Bus_sendPgn65269(Ossm_appData.ambientTemperatureC, Ossm_appData.airInletTemperatureC, Ossm_appData.absoluteBarometricpressurekPa);
        J1939Bus_sendPgn65262(Ossm_appData.coolantTemperatureC, Ossm_appData.fuelTemperatureC, Ossm_appData.oilTemperatureC);
        J1939Bus_sendPgn65129(Ossm_appData.boostTemperatureC, Ossm_appData.coolantTemperatureC);
        J1939Bus_sendPgn65189(Ossm_appData.cacInletTemperatureC, Ossm_appData.transferPipeTemperatureC, Ossm_appData.engineBayTemperatureC);
        J1939Bus_sendPgn65164();
        Ossm_oneSecondMillis = 0;
    }
}

void Ossm_setup(void) {
    Serial.begin(115200);
    uint32_t startTime = millis();
    uint32_t elapsed = millis() - startTime;
    while (!Serial && elapsed < 3000) {
        elapsed = millis() - startTime;
    }
    Serial.println("OSSM Initializing...");
    bool configLoaded = ConfigStorage_loadConfig(Ossm_appConfig);
    if (!configLoaded) {
        Serial.println("Loading default configuration");
        ConfigStorage_loadDefaults(Ossm_appConfig);
        ConfigStorage_saveConfig(Ossm_appConfig);
    } else {
        Serial.println("Configuration loaded from EEPROM");
    }
    ADS1115Manager_initialize(Ossm_appConfig);
    MAX31856Manager_initialize(Ossm_appConfig);
    BME280Manager_initialize(Ossm_appConfig);
    SensorProcessor_initialize(Ossm_appConfig);
    J1939Bus_initialize(Ossm_appData, Ossm_appConfig);
    SerialCommandHandler_initialize();
    Ossm_sensorTimer.begin(Ossm_sensorTimerCallback, 50000);
    Serial.println("OSSM Ready");
}

void Ossm_loop(void) {
    if (Ossm_sensorUpdateReady) {
        Ossm_processSensorUpdates();
        Ossm_sensorUpdateReady = false;
    }
    SerialCommandHandler_update(Ossm_appConfig, Ossm_appData);
    Ossm_sendJ1939Messages();
}
