/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "ossm.h"

// Main OSSM application logic
// Handles sensor polling, J1939 messaging, and command processing
#include <Arduino.h>
#include <AppConfig.h>
#include "../Data/ConfigStorage.h"
#include "../Data/ADS1115Manager.h"
#include "../Data/MAX31856Manager.h"
#include "../Data/BME280Manager.h"
#include "SensorProcessor.h"
#include "CommandHandler.h"
#include <Data/SensorValues.h>
#include <Display/J1939Bus.h>
#include "SerialCommandHandler.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: Ossm */
static IntervalTimer Ossm_sensorTimer = {};
static bool Ossm_sensorUpdateReady = false;
static elapsedMillis Ossm_halfSecondMillis = {};
static elapsedMillis Ossm_oneSecondMillis = {};

void Ossm_sensorTimerCallback(void) {
    Ossm_sensorUpdateReady = true;
}

void Ossm_processSensorUpdates(void) {
    ADS1115Manager_update();
    MAX31856Manager_update();
    BME280Manager_update();
    SensorProcessor_processAllInputs();
}

static void Ossm_populateHardwareFlags(void) {
    for (uint8_t i = 0; i < TEMP_INPUT_COUNT; i = i + 1) {
        EValueId val = appConfig.tempInputs[i].assignedValue;
        if (val != EValueId_VALUE_UNASSIGNED) {
            SensorValues_setHasHardware(val, true);
        }
    }
    for (uint8_t i = 0; i < PRESSURE_INPUT_COUNT; i = i + 1) {
        EValueId val = appConfig.pressureInputs[i].assignedValue;
        if (val != EValueId_VALUE_UNASSIGNED) {
            SensorValues_setHasHardware(val, true);
        }
    }
    if (appConfig.egtEnabled) {
        SensorValues_setHasHardware(EValueId_TURBO1_TURB_INLET_TEMP, true);
    }
    if (appConfig.bme280Enabled) {
        SensorValues_setHasHardware(EValueId_AMBIENT_PRES, true);
        SensorValues_setHasHardware(EValueId_AMBIENT_TEMP, true);
        SensorValues_setHasHardware(EValueId_AMBIENT_HUMIDITY, true);
    }
}

void Ossm_sendJ1939Messages(void) {
    if (Ossm_halfSecondMillis >= 500) {
        J1939Bus_sendPgnGeneric(65270);
        J1939Bus_sendPgnGeneric(65263);
        J1939Bus_sendPgnGeneric(65190);
        Ossm_halfSecondMillis = 0;
    }
    if (Ossm_oneSecondMillis >= 1000) {
        J1939Bus_sendPgnGeneric(65269);
        J1939Bus_sendPgnGeneric(65262);
        J1939Bus_sendPgnGeneric(65129);
        J1939Bus_sendPgnGeneric(65189);
        J1939Bus_sendPgnGeneric(65164);
        Ossm_oneSecondMillis = 0;
    }
}

void Ossm_setup(void) {
    SensorValues_initialize();
    Serial.begin(115200);
    uint32_t startTime = millis();
    uint32_t elapsed = millis() - startTime;
    while (!Serial && elapsed < 3000) {
        elapsed = millis() - startTime;
    }
    Serial.println("OSSM Initializing...");
    bool configLoaded = ConfigStorage_loadConfig(appConfig);
    if (!configLoaded) {
        Serial.println("Loading default configuration");
        ConfigStorage_loadDefaults(appConfig);
        ConfigStorage_saveConfig(appConfig);
    } else {
        Serial.println("Configuration loaded from EEPROM");
    }
    Ossm_populateHardwareFlags();
    ADS1115Manager_initialize(appConfig);
    MAX31856Manager_initialize(appConfig);
    BME280Manager_initialize(appConfig);
    SensorProcessor_initialize();
    J1939Bus_initialize();
    SerialCommandHandler_initialize();
    Ossm_sensorTimer.begin(Ossm_sensorTimerCallback, 50000);
    Serial.println("OSSM Ready");
}

void Ossm_loop(void) {
    if (Ossm_sensorUpdateReady) {
        Ossm_processSensorUpdates();
        Ossm_sensorUpdateReady = false;
    }
    SerialCommandHandler_update();
    Ossm_sendJ1939Messages();
}
