/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "SensorProcessor.h"

// Sensor processing logic
// Reads from hardware managers and stores values in SensorValues
#include <Arduino.h>
#include <AppConfig.h>
#include <Data/ADS1115Manager.h>
#include <Data/MAX31856Manager.h>
#include <Data/BME280Manager.h>
#include <Display/SensorConvert.h>
#include <Display/HardwareMap.h>
#include <Data/SensorValues.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: SensorProcessor */
static bool SensorProcessor_initialized = false;

void SensorProcessor_initialize(void) {
    SensorProcessor_initialized = true;
}

static float SensorProcessor_getAtmosphericPressurekPa(void) {
    float baro = SensorValues_current[EValueId_AMBIENT_PRES].value;
    if (baro > 0.0) {
        return baro;
    }
    return SensorConvert_defaultAtmosphericPressure();
}

static void SensorProcessor_processTempInputs(void) {
    for (uint8_t i = 0; i < TEMP_INPUT_COUNT; i += 1) {
        EValueId val = appConfig.tempInputs[i].assignedValue;
        if (val == EValueId_VALUE_UNASSIGNED) {
            continue;
        }
        uint8_t device = HardwareMap_tempDevice(i);
        uint8_t channel = HardwareMap_tempChannel(i);
        float voltage = ADS1115Manager_getVoltage(device, channel);
        float tempC = SensorConvert_ntcTemperature(voltage, appConfig.tempInputs[i]);
        SensorValues_current[val].value = tempC;
    }
}

static void SensorProcessor_processPressureInputs(void) {
    for (uint8_t i = 0; i < PRESSURE_INPUT_COUNT; i += 1) {
        EValueId val = appConfig.pressureInputs[i].assignedValue;
        if (val == EValueId_VALUE_UNASSIGNED) {
            continue;
        }
        uint8_t device = HardwareMap_pressureDevice(i);
        uint8_t channel = HardwareMap_pressureChannel(i);
        float voltage = ADS1115Manager_getVoltage(device, channel);
        float atm = SensorProcessor_getAtmosphericPressurekPa();
        float pressurekPa = SensorConvert_pressure(voltage, appConfig.pressureInputs[i], atm);
        SensorValues_current[val].value = pressurekPa;
    }
}

static void SensorProcessor_processEgt(void) {
    bool egtReady = MAX31856Manager_isEnabled();
    if (appConfig.egtEnabled && egtReady) {
        float temp = MAX31856Manager_getTemperatureC();
        SensorValues_current[EValueId_TURBO1_TURB_INLET_TEMP].value = temp;
    }
}

static void SensorProcessor_processBme280(void) {
    bool bmeReady = BME280Manager_isEnabled();
    if (appConfig.bme280Enabled && bmeReady) {
        float temp = BME280Manager_getTemperatureC();
        float humidity = BME280Manager_getHumidity();
        float pressure = BME280Manager_getPressurekPa();
        SensorValues_current[EValueId_AMBIENT_TEMP].value = temp;
        SensorValues_current[EValueId_AMBIENT_HUMIDITY].value = humidity;
        SensorValues_current[EValueId_AMBIENT_PRES].value = pressure;
    }
}

void SensorProcessor_processAllInputs(void) {
    if (!SensorProcessor_initialized) {
        return;
    }
    SensorProcessor_processTempInputs();
    SensorProcessor_processPressureInputs();
    SensorProcessor_processEgt();
    SensorProcessor_processBme280();
}
