/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "TCommandResult.h"

#include <stdint.h>

// TCommandResult.cnx - Command result helpers for OSSM
// Provides factory functions for creating command responses
// Query result struct - holds response data for query commands
/* Scope: TCommandResult */

uint8_t TCommandResult_ok(void) {
    return 0;
}

uint8_t TCommandResult_error(uint8_t code) {
    return code;
}
