/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "TimingDebugHandler.h"

/**
 * Timing Debug Handler
 * Monitors loop timing and reports max execution durations
 * Wrap with #ifdef DEBUG_TIMING to exclude from release builds
 */
#include <Arduino.h>
#include <AppConfig.h>

#include <stdint.h>

/* Scope: TimingDebugHandler */
static elapsedMillis TimingDebugHandler_reportTimer = {};
static uint32_t TimingDebugHandler_maxSensor = 0;
static uint32_t TimingDebugHandler_maxSerial = 0;
static uint32_t TimingDebugHandler_maxJ1939 = 0;
static uint32_t TimingDebugHandler_maxTotal = 0;

void TimingDebugHandler_initialize(void) {
    TimingDebugHandler_reportTimer = 0;
    TimingDebugHandler_maxSensor = 0;
    TimingDebugHandler_maxSerial = 0;
    TimingDebugHandler_maxJ1939 = 0;
    TimingDebugHandler_maxTotal = 0;
}

void TimingDebugHandler_recordSensor(uint32_t t0) {
    uint32_t t1 = micros();
    uint32_t duration = t1 - t0;
    if (duration > TimingDebugHandler_maxSensor) {
        TimingDebugHandler_maxSensor = duration;
    }
}

void TimingDebugHandler_recordSerial(uint32_t t0) {
    uint32_t t1 = micros();
    uint32_t duration = t1 - t0;
    if (duration > TimingDebugHandler_maxSerial) {
        TimingDebugHandler_maxSerial = duration;
    }
}

void TimingDebugHandler_recordJ1939(uint32_t t0) {
    uint32_t t1 = micros();
    uint32_t duration = t1 - t0;
    if (duration > TimingDebugHandler_maxJ1939) {
        TimingDebugHandler_maxJ1939 = duration;
    }
    uint32_t total = t1 - t0;
    if (total > TimingDebugHandler_maxTotal) {
        TimingDebugHandler_maxTotal = total;
    }
}

void TimingDebugHandler_maybeReport(void) {
    if (TimingDebugHandler_reportTimer >= 5000) {
        Serial.print("LOOP us max: sensor=");
        Serial.print(TimingDebugHandler_maxSensor);
        Serial.print(" serial=");
        Serial.print(TimingDebugHandler_maxSerial);
        Serial.print(" j1939=");
        Serial.print(TimingDebugHandler_maxJ1939);
        Serial.print(" total=");
        Serial.println(TimingDebugHandler_maxTotal);
        TimingDebugHandler_maxSensor = 0;
        TimingDebugHandler_maxSerial = 0;
        TimingDebugHandler_maxJ1939 = 0;
        TimingDebugHandler_maxTotal = 0;
        TimingDebugHandler_reportTimer = 0;
    }
}
