#ifndef COMMANDHANDLER_H
#define COMMANDHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Data/ConfigStorage.h>
#include <Data/ADS1115Manager.h>
#include <Data/MAX31856Manager.h>
#include <Data/BME280Manager.h>
#include <Display/Presets.h>
#include <Display/SpnCategory.h>
#include <Display/InputValid.h>
#include <Display/AppData.h>
#include <Domain/TCommandResult.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;
typedef struct TQueryResult TQueryResult;

/* Enumerations */
typedef enum {
    ECommandError_OK = 0,
    ECommandError_UNKNOWN_COMMAND = 1,
    ECommandError_PARSE_FAILED = 2,
    ECommandError_UNKNOWN_SPN = 3,
    ECommandError_INVALID_TEMP_INPUT = 4,
    ECommandError_INVALID_PRESSURE_INPUT = 5,
    ECommandError_INVALID_NTC_PARAM = 6,
    ECommandError_INVALID_TC_TYPE = 7,
    ECommandError_INVALID_QUERY_TYPE = 8,
    ECommandError_SAVE_FAILED = 9,
    ECommandError_INVALID_PRESET = 10
} ECommandError;

/* Function prototypes */
uint8_t CommandHandler_enableSpn(AppConfig* cfg, uint16_t spn, uint8_t input);
uint8_t CommandHandler_disableSpn(AppConfig* cfg, uint16_t spn);
uint8_t CommandHandler_setPressureRange(AppConfig* cfg, uint8_t input, uint16_t maxPressure);
uint8_t CommandHandler_setTcType(AppConfig* cfg, uint8_t tcType);
uint8_t CommandHandler_applyNtcPreset(AppConfig* cfg, uint8_t input, uint8_t preset);
uint8_t CommandHandler_applyPressurePreset(AppConfig* cfg, uint8_t input, uint8_t preset);
uint8_t CommandHandler_setNtcParam(AppConfig* cfg, uint8_t input, uint8_t param, float value);
uint8_t CommandHandler_save(const AppConfig* cfg);
uint8_t CommandHandler_reset(const AppConfig* cfg);
uint8_t CommandHandler_querySpnCounts(const AppConfig* cfg, TQueryResult* out);
uint8_t CommandHandler_queryFullConfig(const AppConfig* cfg, TQueryResult* out);
uint8_t CommandHandler_queryTempSpns(const AppConfig* cfg, uint8_t subQuery, TQueryResult* out);
uint8_t CommandHandler_queryPresSpns(const AppConfig* cfg, uint8_t subQuery, TQueryResult* out);

#ifdef __cplusplus
}
#endif

#endif /* COMMANDHANDLER_H */
