#ifndef COMMANDHANDLER_H
#define COMMANDHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Data/ConfigStorage.h>
#include <Domain/Hardware.h>
#include <Display/Presets.h>
#include <Display/InputValid.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    ECommandResult_CMD_SUCCESS = 0,
    ECommandResult_CMD_UNKNOWN_COMMAND = 1,
    ECommandResult_CMD_UNKNOWN_VALUE = 2,
    ECommandResult_CMD_MISSING_VALUE = 3,
    ECommandResult_CMD_MISSING_SENSOR_NUMBER = 4,
    ECommandResult_CMD_INVALID_SENSOR_NUMBER = 5,
    ECommandResult_CMD_INVALID_TC_TYPE = 6,
    ECommandResult_CMD_INVALID_PRESET = 7,
    ECommandResult_CMD_INVALID_NTC_PARAM = 8,
    ECommandResult_CMD_SAVE_FAILED = 9
} ECommandResult;
typedef enum {
    EValueCategory_VALUE_CAT_TEMPERATURE = 0,
    EValueCategory_VALUE_CAT_PRESSURE = 1,
    EValueCategory_VALUE_CAT_EGT = 2,
    EValueCategory_VALUE_CAT_BME280 = 3,
    EValueCategory_VALUE_CAT_UNKNOWN = 4
} EValueCategory;

/* Function prototypes */
EValueCategory CommandHandler_getValueCategory(EValueId valueId);
ECommandResult CommandHandler_setNtcParam(uint8_t input, uint8_t param, float value);
ECommandResult CommandHandler_process(const uint8_t data[8]);

#ifdef __cplusplus
}
#endif

#endif /* COMMANDHANDLER_H */
