#ifndef HARDWARE_H
#define HARDWARE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Data/ADS1115Manager.h>
#include <Data/MAX31856Manager.h>
#include <Data/BME280Manager.h>
#include <Data/SensorValues.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;

/* Function prototypes */
void Hardware_initialize(const AppConfig& config);

#ifdef __cplusplus
}
#endif

#endif /* HARDWARE_H */
