#ifndef HARDWARE_H
#define HARDWARE_H

/**
 * Generated by C-Next Transpiler from: Hardware.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>
#include <Data/ADS1115Manager.hpp>
#include <Data/MAX31856Manager.hpp>
#include <Data/BME280Manager.hpp>
#include <Data/SensorValues.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Hardware_initialize(const AppConfig& config);

#ifdef __cplusplus
}
#endif

#endif /* HARDWARE_H */
