#ifndef J1939COMMANDHANDLER_H
#define J1939COMMANDHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Display/J1939Bus.h>
#include <Domain/CommandHandler.h>
#include <Display/FloatBytes.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void J1939CommandHandler_update(void);

#ifdef __cplusplus
}
#endif

#endif /* J1939COMMANDHANDLER_H */
