#ifndef OSSM_H
#define OSSM_H

/**
 * Generated by C-Next Transpiler from: ossm.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>
#include "../Data/ConfigStorage.hpp"
#include "SensorProcessor.hpp"
#include "Hardware.hpp"
#include <Data/SensorValues.hpp>
#include "J1939CommandHandler.hpp"
#include "SerialCommandHandler.hpp"
#include "TimingDebugHandler.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Ossm_setup(void);
void Ossm_loop(void);

#ifdef __cplusplus
}
#endif

#endif /* OSSM_H */
