#ifndef OSSM_H
#define OSSM_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include "../Data/ConfigStorage.h"
#include "../Data/ADS1115Manager.h"
#include "../Data/MAX31856Manager.h"
#include "../Data/BME280Manager.h"
#include "SensorProcessor.h"
#include "Hardware.h"
#include <Data/SensorValues.h>
#include <Display/J1939Bus.h>
#include "SerialCommandHandler.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Ossm_sensorTimerCallback(void);
void Ossm_processSensorUpdates(void);
void Ossm_sendJ1939Messages(void);
void Ossm_setup(void);
void Ossm_loop(void);

#ifdef __cplusplus
}
#endif

#endif /* OSSM_H */
