#ifndef OSSM_H
#define OSSM_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include "../Data/ConfigStorage.h"
#include "SensorProcessor.h"
#include "Hardware.h"
#include <Data/SensorValues.h>
#include "J1939CommandHandler.h"
#include "SerialCommandHandler.h"
#include "TimingDebugHandler.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Ossm_setup(void);
void Ossm_loop(void);

#ifdef __cplusplus
}
#endif

#endif /* OSSM_H */
