#ifndef SENSORPROCESSOR_H
#define SENSORPROCESSOR_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>
#include <Data/ADS1115Manager.hpp>
#include <Data/MAX31856Manager.hpp>
#include <Data/BME280Manager.hpp>
#include <Display/SensorConvert.hpp>
#include <Display/HardwareMap.hpp>
#include <Data/SensorValues.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void SensorProcessor_initialize(void);
void SensorProcessor_update(void);

#ifdef __cplusplus
}
#endif

#endif /* SENSORPROCESSOR_H */
