#ifndef SENSORPROCESSOR_H
#define SENSORPROCESSOR_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Data/ADS1115Manager.h>
#include <Data/MAX31856Manager.h>
#include <Data/BME280Manager.h>
#include <Display/SensorConvert.h>
#include <Display/HardwareMap.h>
#include <Display/AppData.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;
typedef struct AppData AppData;

/* Function prototypes */
void SensorProcessor_initialize(const AppConfig* cfg);
void SensorProcessor_processAllInputs(AppData* appData);

#ifdef __cplusplus
}
#endif

#endif /* SENSORPROCESSOR_H */
