#ifndef SERIALCOMMANDHANDLER_H
#define SERIALCOMMANDHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>
#include <Domain/CommandHandler.hpp>
#include <Display/FaultDecode.hpp>
#include <Data/ADS1115Manager.hpp>
#include <Data/MAX31856Manager.hpp>
#include <Data/SensorValues.hpp>
#include <Display/ValueName.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern char cmdBuffer[129];
extern uint8_t cmdIndex;

/* Function prototypes */
void SerialCommandHandler_initialize(void);
void SerialCommandHandler_update(void);

#ifdef __cplusplus
}
#endif

#endif /* SERIALCOMMANDHANDLER_H */
