#ifndef TCOMMANDRESULT_H
#define TCOMMANDRESULT_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TQueryResult {
    uint8_t data[6];
    uint8_t len;
} TQueryResult;

/* Function prototypes */
uint8_t TCommandResult_ok(void);
uint8_t TCommandResult_error(uint8_t code);

#ifdef __cplusplus
}
#endif

#endif /* TCOMMANDRESULT_H */
