#ifndef TIMINGDEBUGHANDLER_H
#define TIMINGDEBUGHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void TimingDebugHandler_initialize(void);
void TimingDebugHandler_recordSensor(uint32_t t0);
void TimingDebugHandler_recordSerial(uint32_t t0);
void TimingDebugHandler_recordJ1939(uint32_t t0);
void TimingDebugHandler_maybeReport(void);

#ifdef __cplusplus
}
#endif

#endif /* TIMINGDEBUGHANDLER_H */
