#ifndef TIMINGDEBUGHANDLER_H
#define TIMINGDEBUGHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void TimingDebugHandler_initialize(void);
void TimingDebugHandler_startSensor(void);
void TimingDebugHandler_finishSensor(void);
void TimingDebugHandler_startSerial(void);
void TimingDebugHandler_finishSerial(void);
void TimingDebugHandler_startJ1939(void);
void TimingDebugHandler_finishJ1939(void);
void TimingDebugHandler_maybeReport(void);

#ifdef __cplusplus
}
#endif

#endif /* TIMINGDEBUGHANDLER_H */
