/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// Physical measurement locations
// Named by position in air/exhaust path, not by J1939 SPN names
typedef enum {
    EValueId_AMBIENT_PRES = 0,
    EValueId_AMBIENT_TEMP = 1,
    EValueId_AMBIENT_HUMIDITY = 2,
    EValueId_TURBO1_COMP_INLET_PRES = 3,
    EValueId_TURBO1_COMP_INLET_TEMP = 4,
    EValueId_TURBO1_COMP_OUTLET_PRES = 5,
    EValueId_TURBO1_COMP_OUTLET_TEMP = 6,
    EValueId_TURBO1_TURB_INLET_TEMP = 7,
    EValueId_CAC1_INLET_PRES = 8,
    EValueId_CAC1_INLET_TEMP = 9,
    EValueId_CAC1_OUTLET_PRES = 10,
    EValueId_CAC1_OUTLET_TEMP = 11,
    EValueId_MANIFOLD1_ABS_PRES = 12,
    EValueId_MANIFOLD1_TEMP = 13,
    EValueId_OIL_PRES = 14,
    EValueId_OIL_TEMP = 15,
    EValueId_COOLANT_PRES = 16,
    EValueId_COOLANT_TEMP = 17,
    EValueId_FUEL_PRES = 18,
    EValueId_FUEL_TEMP = 19,
    EValueId_ENGINE_BAY_TEMP = 20,
    EValueId_VALUE_ID_COUNT = 21,
    EValueId_VALUE_UNASSIGNED = 255
} EValueId;
