/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

/**
 * ADC reading structure used throughout the project.
 * rawValue   - The signed 16-bit result from the ADS1115 conversion.
 * timestamp  - Milliseconds (from millis()) when the conversion completed.
 * valid      - Flag indicating whether the reading is fresh/valid.
 */
typedef struct TAdcReading {
    int16_t rawValue;
    uint32_t timestamp;
    bool valid;
} TAdcReading;
