/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// PGN transmission configuration
// Defines PGN timing and properties per J1939 spec
typedef struct TPgnConfig {
    uint16_t pgn;
    uint16_t intervalMs;
    uint8_t dataLength;
    uint8_t priority;
} TPgnConfig;
