/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// SPN encoding configuration
// Maps J1939 SPNs to physical values with encoding parameters
#include "EValueId.h"

#include <stdint.h>

typedef struct TSpnConfig {
    uint16_t spn;
    uint16_t pgn;
    uint8_t bytePos;
    uint8_t dataLength;
    float resolution;
    float offset;
    EValueId source;
} TSpnConfig;
