#ifndef ADS1115MANAGER_H
#define ADS1115MANAGER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../AppConfig.h"
#include <Display/HardwareMap.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;
typedef struct TAdcReading TAdcReading;

/* Function prototypes */
void ADS1115Manager_initialize(const AppConfig* config);
bool ADS1115Manager_update(void);
TAdcReading ADS1115Manager_getReading(uint8_t device, uint8_t channel);
float ADS1115Manager_getVoltage(uint8_t device, uint8_t channel);
bool ADS1115Manager_isDeviceEnabled(uint8_t device);

#ifdef __cplusplus
}
#endif

#endif /* ADS1115MANAGER_H */
