#ifndef ADS1115MANAGER_H
#define ADS1115MANAGER_H

/**
 * Generated by C-Next Transpiler from: ADS1115Manager.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../AppConfig.hpp"
#include "types/TAdcReading.hpp"
#include <Display/HardwareMap.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void ADS1115Manager_initialize(const AppConfig& config);
bool ADS1115Manager_update(void);
TAdcReading ADS1115Manager_getReading(uint8_t device, uint8_t channel);
float ADS1115Manager_getVoltage(uint8_t device, uint8_t channel);
bool ADS1115Manager_isDeviceEnabled(uint8_t device);
void ADS1115Manager_printDebugInfo(void);

#ifdef __cplusplus
}
#endif

#endif /* ADS1115MANAGER_H */
