#ifndef BME280MANAGER_H
#define BME280MANAGER_H

/**
 * Generated by C-Next Transpiler from: BME280Manager.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
bool BME280Manager_update(void);
void BME280Manager_initialize(const AppConfig& config);
float BME280Manager_getTemperatureC(void);
float BME280Manager_getHumidity(void);
float BME280Manager_getPressurekPa(void);
bool BME280Manager_isEnabled(void);

#ifdef __cplusplus
}
#endif

#endif /* BME280MANAGER_H */
