#ifndef CONFIGSTORAGE_H
#define CONFIGSTORAGE_H

/**
 * Generated by C-Next Transpiler from: ConfigStorage.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>
#include <Display/Crc32.hpp>
#include "../AppConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
bool ConfigStorage_validateConfig(const AppConfig& config);
void ConfigStorage_loadDefaults(AppConfig& config);
bool ConfigStorage_saveConfig(const AppConfig& config);
void ConfigStorage_loadConfig(AppConfig& config);

#ifdef __cplusplus
}
#endif

#endif /* CONFIGSTORAGE_H */
