#ifndef J1939CONFIG_H
#define J1939CONFIG_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "types/EValueId.hpp"
#include "types/TSpnConfig.hpp"
#include "types/TPgnConfig.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const TSpnConfig SPN_CONFIGS[20];
extern const uint8_t SPN_CONFIG_COUNT;
extern const TPgnConfig PGN_CONFIGS[8];
extern const uint8_t PGN_CONFIG_COUNT;

/* Function prototypes */
EValueId J1939Config_findSourceForSpn(uint16_t spn);

#ifdef __cplusplus
}
#endif

#endif /* J1939CONFIG_H */
