#ifndef MAX31856MANAGER_H
#define MAX31856MANAGER_H

/**
 * Generated by C-Next Transpiler from: MAX31856Manager.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../AppConfig.h"
#include <Adafruit_MAX31856.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t thermoCoupleCs;
extern Adafruit_MAX31856 thermocouple;

/* Function prototypes */
void MAX31856Manager_initialize(const AppConfig& config);
bool MAX31856Manager_update(void);
float MAX31856Manager_getTemperatureC(void);
float MAX31856Manager_getColdJunctionC(void);
bool MAX31856Manager_isEnabled(void);
uint8_t MAX31856Manager_getFaultStatus(void);

#ifdef __cplusplus
}
#endif

#endif /* MAX31856MANAGER_H */
