#ifndef SENSORVALUES_H
#define SENSORVALUES_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "types/EValueId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TSensorValue {
    float value;
    bool hasHardware;
} TSensorValue;

/* External variables */
extern TSensorValue SensorValues_current[EValueId_VALUE_ID_COUNT];

/* Function prototypes */
void SensorValues_initialize(void);

#ifdef __cplusplus
}
#endif

#endif /* SENSORVALUES_H */
