#ifndef SENSORVALUES_H
#define SENSORVALUES_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "types/EValueId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void SensorValues_initialize(void);
float SensorValues_get(EValueId id);
void SensorValues_set(EValueId id, float value);
void SensorValues_setHasHardware(EValueId id, bool has);
bool SensorValues_getHasHardware(EValueId id);

#ifdef __cplusplus
}
#endif

#endif /* SENSORVALUES_H */
