/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// Application sensor data structure
// Holds all current sensor readings
typedef struct {
    float humidity;
    float ambientTemperatureC;
    float absoluteBarometricpressurekPa;
    float oilTemperatureC;
    float oilPressurekPa;
    float coolantTemperatureC;
    float coolantPressurekPa;
    float transferPipeTemperatureC;
    float transferPipePressurekPa;
    float boostPressurekPa;
    float boostTemperatureC;
    float cacInletPressurekPa;
    float cacInletTemperatureC;
    float airInletPressurekPa;
    float airInletTemperatureC;
    float fuelPressurekPa;
    float fuelTemperatureC;
    float engineBayTemperatureC;
    float egtTemperatureC;
} AppData;
