#ifndef BYTEUTILS_H
#define BYTEUTILS_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint16_t ByteUtils_makeU16BE(uint8_t high, uint8_t low);
uint16_t ByteUtils_makeU16LE(uint8_t low, uint8_t high);
uint8_t ByteUtils_highByte(uint16_t value);
uint8_t ByteUtils_lowByte(uint16_t value);
uint32_t ByteUtils_makeU32BE(uint8_t b3, uint8_t b2, uint8_t b1, uint8_t b0);
uint32_t ByteUtils_makeU32LE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3);
uint8_t ByteUtils_byte0(uint32_t value);
uint8_t ByteUtils_byte1(uint32_t value);
uint8_t ByteUtils_byte2(uint32_t value);
uint8_t ByteUtils_byte3(uint32_t value);
bool ByteUtils_isBitSet(uint8_t value, uint8_t bit);
uint8_t ByteUtils_setBit(uint8_t value, uint8_t bit);
uint8_t ByteUtils_clearBit(uint8_t value, uint8_t bit);
uint8_t ByteUtils_clampU8(uint8_t value, uint8_t minVal, uint8_t maxVal);
uint16_t ByteUtils_clampU16(uint16_t value, uint16_t minVal, uint16_t maxVal);

#ifdef __cplusplus
}
#endif

#endif /* BYTEUTILS_H */
