/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "ByteUtils.h"

// Byte Utility Functions
// Common byte manipulation operations for embedded systems
// Tests bit shifting, masking, and byte extraction patterns
#include <stdint.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: ByteUtils */

uint16_t ByteUtils_makeU16BE(uint8_t high, uint8_t low) {
    uint16_t h = high;
    uint16_t l = low;
    uint16_t result = (h << 8) | l;
    return result;
}

uint16_t ByteUtils_makeU16LE(uint8_t low, uint8_t high) {
    uint16_t h = high;
    uint16_t l = low;
    uint16_t result = (h << 8) | l;
    return result;
}

uint8_t ByteUtils_highByte(uint16_t value) {
    uint8_t result = (value >> 8) & 0xFF;
    return result;
}

uint8_t ByteUtils_lowByte(uint16_t value) {
    uint8_t result = value & 0xFF;
    return result;
}

uint32_t ByteUtils_makeU32BE(uint8_t b3, uint8_t b2, uint8_t b1, uint8_t b0) {
    uint32_t byte3 = b3;
    uint32_t byte2 = b2;
    uint32_t byte1 = b1;
    uint32_t byte0 = b0;
    uint32_t result = (byte3 << 24) | (byte2 << 16) | (byte1 << 8) | byte0;
    return result;
}

uint32_t ByteUtils_makeU32LE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3) {
    uint32_t byte3 = b3;
    uint32_t byte2 = b2;
    uint32_t byte1 = b1;
    uint32_t byte0 = b0;
    uint32_t result = (byte3 << 24) | (byte2 << 16) | (byte1 << 8) | byte0;
    return result;
}

uint8_t ByteUtils_byte0(uint32_t value) {
    uint8_t result = value & 0xFF;
    return result;
}

uint8_t ByteUtils_byte1(uint32_t value) {
    uint8_t result = (value >> 8) & 0xFF;
    return result;
}

uint8_t ByteUtils_byte2(uint32_t value) {
    uint8_t result = (value >> 16) & 0xFF;
    return result;
}

uint8_t ByteUtils_byte3(uint32_t value) {
    uint8_t result = (value >> 24) & 0xFF;
    return result;
}

bool ByteUtils_isBitSet(uint8_t value, uint8_t bit) {
    if (bit > 7) {
        return false;
    }
    uint8_t mask = 1 << bit;
    if ((value & mask) != 0) {
        return true;
    }
    return false;
}

uint8_t ByteUtils_setBit(uint8_t value, uint8_t bit) {
    if (bit > 7) {
        return value;
    }
    uint8_t mask = 1 << bit;
    uint8_t result = value | mask;
    return result;
}

uint8_t ByteUtils_clearBit(uint8_t value, uint8_t bit) {
    if (bit > 7) {
        return value;
    }
    uint8_t mask = 1 << bit;
    uint8_t invMask = ~mask;
    uint8_t result = value & invMask;
    return result;
}

uint8_t ByteUtils_clampU8(uint8_t value, uint8_t minVal, uint8_t maxVal) {
    if (value < minVal) {
        return minVal;
    }
    if (value > maxVal) {
        return maxVal;
    }
    return value;
}

uint16_t ByteUtils_clampU16(uint16_t value, uint16_t minVal, uint16_t maxVal) {
    if (value < minVal) {
        return minVal;
    }
    if (value > maxVal) {
        return maxVal;
    }
    return value;
}
