#ifndef CRC32_H
#define CRC32_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
struct AppConfig;

/* Function prototypes */
uint32_t crc32_calculateChecksum(const AppConfig* config);

#ifdef __cplusplus
}
#endif

#endif /* CRC32_H */
