#ifndef FAULT_DECODE_H
#define FAULT_DECODE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t fault_decode_FAULT_OPEN;
extern const uint8_t fault_decode_FAULT_OVUV;
extern const uint8_t fault_decode_FAULT_TC_LOW;
extern const uint8_t fault_decode_FAULT_TC_HIGH;
extern const uint8_t fault_decode_FAULT_CJ_LOW;
extern const uint8_t fault_decode_FAULT_CJ_HIGH;
extern const uint8_t fault_decode_FAULT_TC_RANGE;
extern const uint8_t fault_decode_FAULT_CJ_RANGE;
extern const uint8_t fault_decode_IDX_OPEN;
extern const uint8_t fault_decode_IDX_OVUV;
extern const uint8_t fault_decode_IDX_TC_LOW;
extern const uint8_t fault_decode_IDX_TC_HIGH;
extern const uint8_t fault_decode_IDX_CJ_LOW;
extern const uint8_t fault_decode_IDX_CJ_HIGH;
extern const uint8_t fault_decode_IDX_TC_RANGE;
extern const uint8_t fault_decode_IDX_CJ_RANGE;

/* Function prototypes */
bool fault_decode_hasFault(uint8_t faultCode);
bool fault_decode_isOpen(uint8_t faultCode);
bool fault_decode_isOvuv(uint8_t faultCode);
bool fault_decode_isTcLow(uint8_t faultCode);
bool fault_decode_isTcHigh(uint8_t faultCode);
bool fault_decode_isCjLow(uint8_t faultCode);
bool fault_decode_isCjHigh(uint8_t faultCode);
bool fault_decode_isTcRange(uint8_t faultCode);
bool fault_decode_isCjRange(uint8_t faultCode);
uint8_t fault_decode_getFirstFaultIndex(uint8_t faultCode);
uint8_t fault_decode_countFaults(uint8_t faultCode);
bool fault_decode_isCritical(uint8_t faultCode);

#ifdef __cplusplus
}
#endif

#endif /* FAULT_DECODE_H */
