/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Display/FloatBytes.h"

#include <stdint.h>
#include <stdbool.h>

// Float Byte Utilities
// IEEE 754 float reconstruction from byte arrays
// Used in J1939 command parsing for float parameter values
/* Scope: FloatBytes */

float FloatBytes_fromBytesLE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3) {
    float result = 0.0;
    result = (result & ~(0xFFU << 0)) | ((b0 & 0xFFU) << 0);
    result = (result & ~(0xFFU << 8)) | ((b1 & 0xFFU) << 8);
    result = (result & ~(0xFFU << 16)) | ((b2 & 0xFFU) << 16);
    result = (result & ~(0xFFU << 24)) | ((b3 & 0xFFU) << 24);
    return result;
}

float FloatBytes_fromBytesBE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3) {
    float result = 0.0;
    result = (result & ~(0xFFU << 0)) | ((b3 & 0xFFU) << 0);
    result = (result & ~(0xFFU << 8)) | ((b2 & 0xFFU) << 8);
    result = (result & ~(0xFFU << 16)) | ((b1 & 0xFFU) << 16);
    result = (result & ~(0xFFU << 24)) | ((b0 & 0xFFU) << 24);
    return result;
}

uint8_t FloatBytes_getByte0(float value) {
    return ((value) & 0xFFU);
}

uint8_t FloatBytes_getByte1(float value) {
    return ((value >> 8) & 0xFFU);
}

uint8_t FloatBytes_getByte2(float value) {
    return ((value >> 16) & 0xFFU);
}

uint8_t FloatBytes_getByte3(float value) {
    return ((value >> 24) & 0xFFU);
}

bool FloatBytes_isValidFloat(float value) {
    if (value != value) {
        return false;
    }
    if (value > 3.4e38) {
        return false;
    }
    if (value < -3.4e38) {
        return false;
    }
    return true;
}
