#ifndef FLOAT_BYTES_H
#define FLOAT_BYTES_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
float float_bytes_fromBytesLE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3);
float float_bytes_fromBytesBE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3);
uint8_t float_bytes_getByte0(float value);
uint8_t float_bytes_getByte1(float value);
uint8_t float_bytes_getByte2(float value);
uint8_t float_bytes_getByte3(float value);
bool float_bytes_isValidFloat(float value);

#ifdef __cplusplus
}
#endif

#endif /* FLOAT_BYTES_H */
