#ifndef HARDWAREMAP_H
#define HARDWAREMAP_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t TEMP_COUNT;
extern const uint8_t PRES_COUNT;

/* Function prototypes */
uint8_t HardwareMap_tempDevice(uint8_t input);
uint8_t HardwareMap_tempChannel(uint8_t input);
uint8_t HardwareMap_pressureDevice(uint8_t input);
uint8_t HardwareMap_pressureChannel(uint8_t input);
uint8_t HardwareMap_adsI2cAddress(uint8_t device);
bool HardwareMap_isValidTempInput(uint8_t input);
bool HardwareMap_isValidPressureInput(uint8_t input);

#ifdef __cplusplus
}
#endif

#endif /* HARDWAREMAP_H */
