/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "HardwareMap.h"

// Hardware Mapping Functions
// Maps logical sensor inputs to physical ADS1115 device/channel pairs
// Tests lookup table patterns with multiple return values
#include <stdint.h>

#include <stdint.h>
#include <stdbool.h>

// Temperature input count (8 inputs)
const uint8_t TEMP_COUNT = 8;

// Pressure input count (7 inputs)
const uint8_t PRES_COUNT = 7;

/* Scope: HardwareMap */

uint8_t HardwareMap_tempDevice(uint8_t input) {
    if (input >= TEMP_COUNT) {
        return 0xFF;
    }
    if (input == 0) {
        return 0;
    }
    if (input == 1) {
        return 0;
    }
    if (input == 2) {
        return 1;
    }
    if (input == 3) {
        return 1;
    }
    if (input == 4) {
        return 2;
    }
    if (input == 5) {
        return 2;
    }
    if (input == 6) {
        return 3;
    }
    if (input == 7) {
        return 3;
    }
    return 0xFF;
}

uint8_t HardwareMap_tempChannel(uint8_t input) {
    if (input >= TEMP_COUNT) {
        return 0xFF;
    }
    if (input == 0) {
        return 0;
    }
    if (input == 1) {
        return 2;
    }
    if (input == 2) {
        return 0;
    }
    if (input == 3) {
        return 3;
    }
    if (input == 4) {
        return 1;
    }
    if (input == 5) {
        return 2;
    }
    if (input == 6) {
        return 1;
    }
    if (input == 7) {
        return 2;
    }
    return 0xFF;
}

uint8_t HardwareMap_pressureDevice(uint8_t input) {
    if (input >= PRES_COUNT) {
        return 0xFF;
    }
    if (input == 0) {
        return 0;
    }
    if (input == 1) {
        return 0;
    }
    if (input == 2) {
        return 2;
    }
    if (input == 3) {
        return 2;
    }
    if (input == 4) {
        return 1;
    }
    if (input == 5) {
        return 1;
    }
    if (input == 6) {
        return 3;
    }
    return 0xFF;
}

uint8_t HardwareMap_pressureChannel(uint8_t input) {
    if (input >= PRES_COUNT) {
        return 0xFF;
    }
    if (input == 0) {
        return 1;
    }
    if (input == 1) {
        return 3;
    }
    if (input == 2) {
        return 0;
    }
    if (input == 3) {
        return 3;
    }
    if (input == 4) {
        return 1;
    }
    if (input == 5) {
        return 2;
    }
    if (input == 6) {
        return 0;
    }
    return 0xFF;
}

uint8_t HardwareMap_adsI2cAddress(uint8_t device) {
    if (device == 0) {
        return 0x48;
    }
    if (device == 1) {
        return 0x49;
    }
    if (device == 2) {
        return 0x4A;
    }
    if (device == 3) {
        return 0x4B;
    }
    return 0;
}

bool HardwareMap_isValidTempInput(uint8_t input) {
    if (input < 1) {
        return false;
    }
    if (input > TEMP_COUNT) {
        return false;
    }
    return true;
}

bool HardwareMap_isValidPressureInput(uint8_t input) {
    if (input < 1) {
        return false;
    }
    if (input > PRES_COUNT) {
        return false;
    }
    return true;
}
