#ifndef INPUT_VALID_H
#define INPUT_VALID_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t input_valid_TEMP_COUNT;
extern const uint8_t input_valid_PRESSURE_COUNT;
extern const uint8_t input_valid_NTC_PARAM_COUNT;

/* Function prototypes */
bool input_valid_isValidTempInput(uint8_t input);
bool input_valid_isValidTempIndex(uint8_t index);
uint8_t input_valid_tempInputToIndex(uint8_t input);
uint8_t input_valid_tempIndexToInput(uint8_t index);
bool input_valid_isValidPressureInput(uint8_t input);
bool input_valid_isValidPressureIndex(uint8_t index);
uint8_t input_valid_pressureInputToIndex(uint8_t input);
uint8_t input_valid_pressureIndexToInput(uint8_t index);
bool input_valid_isValidNtcParam(uint8_t param);
bool input_valid_isValidQueryType(uint8_t queryType);
bool input_valid_isValidSubQuery(uint8_t subQuery);
bool input_valid_isValidJ1939Address(uint8_t address);
bool input_valid_isValidAdsDevice(uint8_t device);
bool input_valid_isValidAdsChannel(uint8_t channel);

#ifdef __cplusplus
}
#endif

#endif /* INPUT_VALID_H */
