/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "j1939_bus.h"

// J1939 CAN Bus Communication
// Handles J1939 message transmission and configuration commands
#include "J1939Bus.h"
#include <app_data.h>
#include "AppConfig.h"
#include "FlexCAN_T4.h"
#include "Domain/CommandHandler/CommandHandler.h"
#include <j1939_encode.h>
#include <j1939_decode.h>
#include <spn_check.h>
#include <float_bytes.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: j1939_bus */
static FlexCAN_T4<CAN1,RX_SIZE_256,TX_SIZE_16> j1939_bus_canBus = 0;
static AppData j1939_bus_appData = {0};
static AppConfig j1939_bus_config = {0};

static uint32_t j1939_bus_buildCanId(uint16_t pgn, uint8_t priority, uint8_t sourceAddr) {
    uint32_t id = (static_cast<uint32_t>(priority) << 26) | (static_cast<uint32_t>(pgn) << 8) | static_cast<uint32_t>(sourceAddr);
    return id;
}

static void j1939_bus_fillBuffer(uint8_t buf) {
    for (uint8_t i = 0; i < 8; i += 1) {
        buf = (buf & ~(1 << i)) | ((0xFF ? 1 : 0) << i);
    }
}

static void j1939_bus_sendMessage(uint16_t pgn, const uint8_t buf) {
    CAN_message_t msg = {0};
    msg.flags.extended = 1;
    msg.id = j1939_bus_buildCanId(pgn, 6, j1939_bus_config.j1939SourceAddress);
    msg.len = 8;
    for (uint8_t i = 0; i < 8; i += 1) {
        msg.buf[i] = ((buf >> i) & 1);
    }
    j1939_bus_canBus.write(msg);
}

void j1939_bus_sendConfigResponse(uint8_t cmd, uint8_t errCode, const uint8_t data, uint8_t dataLen) {
    uint8_t buf[8] = {0};
    buf[0] = cmd;
    buf[1] = errCode;
    for (uint8_t i = 0; i < 6; i += 1) {
        if (i < dataLen) {
            buf[2 + i] = ((data >> i) & 1);
        } else {
            buf[2 + i] = 0xFF;
        }
    }
    CAN_message_t msg = {0};
    msg.flags.extended = 1;
    msg.id = j1939_bus_buildCanId(65281, 6, j1939_bus_config.j1939SourceAddress);
    msg.len = 8;
    for (uint8_t i = 0; i < 8; i += 1) {
        msg.buf[i] = buf[i];
    }
    j1939_bus_canBus.write(msg);
}

static void j1939_bus_handleEnableSpn(const uint8_t data) {
    uint16_t spn = j1939_decode.getSpn(data);
    bool enable = j1939_decode.getEnable(data);
    uint8_t input = j1939_decode.getInput(data);
    TCommandResult result = CommandHandler.enableSpn(spn, enable, input);
    j1939_bus_sendConfigResponse(1, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleSetNtcParam(const uint8_t data) {
    uint8_t input = j1939_decode.getNtcInput(data);
    uint8_t param = j1939_decode.getNtcParam(data);
    float value = float_bytes.fromBytesLE(((data >> 3) & 1), ((data >> 4) & 1), ((data >> 5) & 1), ((data >> 6) & 1));
    TCommandResult result = CommandHandler.setNtcParam(input, param, value);
    j1939_bus_sendConfigResponse(2, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleSetPressureRange(const uint8_t data) {
    uint8_t input = j1939_decode.getPressureInput(data);
    uint16_t maxPsi = j1939_decode.getMaxPressure(data);
    TCommandResult result = CommandHandler.setPressureRange(input, maxPsi);
    j1939_bus_sendConfigResponse(3, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleSetTcType(const uint8_t data) {
    uint8_t tcType = j1939_decode.getTcType(data);
    TCommandResult result = CommandHandler.setTcType(tcType);
    j1939_bus_sendConfigResponse(4, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleQuery(const uint8_t data) {
    uint8_t queryType = j1939_decode.getQueryType(data);
    uint8_t subQuery = j1939_decode.getSubQuery(data);
    TCommandResult result = {0};
    switch (queryType) {
        case 0: {
            result = CommandHandler.querySpnCounts();
            break;
        }
        case 1: {
            result = CommandHandler.queryTempSpns(subQuery);
            break;
        }
        case 2: {
            result = CommandHandler.queryPresSpns(subQuery);
            break;
        }
        case 4: {
            result = CommandHandler.queryFullConfig();
            break;
        }
        default: {
            result = TCommandResult.error(ECommandError.INVALID_QUERY_TYPE);
            break;
        }
    }
    j1939_bus_sendConfigResponse(5, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleSave(void) {
    TCommandResult result = CommandHandler.save();
    j1939_bus_sendConfigResponse(6, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleReset(void) {
    TCommandResult result = CommandHandler.reset();
    j1939_bus_sendConfigResponse(7, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handleNtcPreset(const uint8_t data) {
    uint8_t input = j1939_decode.getPresetInput(data);
    uint8_t preset = j1939_decode.getPresetId(data);
    TCommandResult result = CommandHandler.applyNtcPreset(input, preset);
    j1939_bus_sendConfigResponse(8, result.errorCode, result.data, result.dataLen);
}

static void j1939_bus_handlePressurePreset(const uint8_t data) {
    uint8_t input = j1939_decode.getPresetInput(data);
    uint8_t preset = j1939_decode.getPresetId(data);
    TCommandResult result = CommandHandler.applyPressurePreset(input, preset);
    j1939_bus_sendConfigResponse(9, result.errorCode, result.data, result.dataLen);
}

void j1939_bus_processConfigCommand(const uint8_t data, uint8_t len) {
    if (len < 1) {
        return;
    }
    uint8_t cmd = ((data >> 0) & 1);
    switch (cmd) {
        case 1: {
            j1939_bus_handleEnableSpn(data);
            break;
        }
        case 2: {
            j1939_bus_handleSetNtcParam(data);
            break;
        }
        case 3: {
            j1939_bus_handleSetPressureRange(data);
            break;
        }
        case 4: {
            j1939_bus_handleSetTcType(data);
            break;
        }
        case 5: {
            j1939_bus_handleQuery(data);
            break;
        }
        case 6: {
            j1939_bus_handleSave();
            break;
        }
        case 7: {
            j1939_bus_handleReset();
            break;
        }
        case 8: {
            j1939_bus_handleNtcPreset(data);
            break;
        }
        case 9: {
            j1939_bus_handlePressurePreset(data);
            break;
        }
        default: {
            uint8_t empty[1] = {0};
            j1939_bus_sendConfigResponse(cmd, 1, empty, 0);
            break;
        }
    }
}

static void j1939_bus_sniffDataPrivate(const CAN_message_t* msg) {
    J1939Message message = {0};
    message.setCanId((*msg).id);
    message.setData((*msg).buf);
    if (message.pgn == 65280) {
        j1939_bus_processConfigCommand((*msg).buf, 8);
        return;
    }
    if (message.pgn == 59904) {
        j1939_bus_canBus.write((*msg));
    }
}

void j1939_bus_initialize(const AppData* currentData, const AppConfig* cfg) {
    j1939_bus_appData = (*currentData);
    j1939_bus_config = (*cfg);
    Serial.println("J1939 Bus initializing");
    j1939_bus_canBus.begin();
    j1939_bus_canBus.setBaudRate(250000);
    j1939_bus_canBus.setMaxMB(16);
    j1939_bus_canBus.enableFIFO();
    j1939_bus_canBus.enableFIFOInterrupt();
    j1939_bus_canBus.onReceive(j1939_bus_sniffDataPrivate);
    j1939_bus_canBus.mailboxStatus();
    Serial.print("J1939 Source Address: ");
    Serial.println(j1939_bus_config.j1939SourceAddress);
}

void j1939_bus_sendPgn65129(float intakeTemp, float coolantTemp) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn1363 = spn_check.isSpnEnabled(j1939_bus_config, 1363);
    bool spn1637 = spn_check.isSpnEnabled(j1939_bus_config, 1637);
    if (spn1363) {
        uint16_t encoded = j1939_encode.temp16bit(intakeTemp);
        buf[0] = ((encoded) & 0xFFU);
        buf[1] = ((encoded >> 8) & 0xFFU);
    }
    if (spn1637) {
        uint16_t encoded = j1939_encode.temp16bit(coolantTemp);
        buf[2] = ((encoded) & 0xFFU);
        buf[3] = ((encoded >> 8) & 0xFFU);
    }
    j1939_bus_sendMessage(65129, buf);
}

void j1939_bus_sendPgn65164(void) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn441 = spn_check.isSpnEnabled(j1939_bus_config, 441);
    bool spn354 = spn_check.isSpnEnabled(j1939_bus_config, 354);
    if (spn441) {
        buf[0] = j1939_encode.temp8bit(j1939_bus_appData.engineBayTemperatureC);
    }
    if (spn354) {
        buf[6] = j1939_encode.humidity(j1939_bus_appData.humidity);
    }
    j1939_bus_sendMessage(65164, buf);
}

void j1939_bus_sendPgn65189(float intake2Temp, float intake3Temp, float intake4Temp) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn1131 = spn_check.isSpnEnabled(j1939_bus_config, 1131);
    bool spn1132 = spn_check.isSpnEnabled(j1939_bus_config, 1132);
    bool spn1133 = spn_check.isSpnEnabled(j1939_bus_config, 1133);
    if (spn1131) {
        buf[0] = j1939_encode.temp8bit(intake2Temp);
    }
    if (spn1132) {
        buf[1] = j1939_encode.temp8bit(intake3Temp);
    }
    if (spn1133) {
        buf[2] = j1939_encode.temp8bit(intake4Temp);
    }
    j1939_bus_sendMessage(65189, buf);
}

void j1939_bus_sendPgn65190(float boost1kPa, float boost2kPa) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn1127 = spn_check.isSpnEnabled(j1939_bus_config, 1127);
    bool spn1128 = spn_check.isSpnEnabled(j1939_bus_config, 1128);
    if (spn1127) {
        uint16_t encoded = j1939_encode.boost16bit(boost1kPa);
        buf[0] = ((encoded) & 0xFFU);
        buf[1] = ((encoded >> 8) & 0xFFU);
    }
    if (spn1128) {
        uint16_t encoded = j1939_encode.boost16bit(boost2kPa);
        buf[2] = ((encoded) & 0xFFU);
        buf[3] = ((encoded >> 8) & 0xFFU);
    }
    j1939_bus_sendMessage(65190, buf);
}

void j1939_bus_sendPgn65262(float coolantTemp, float fuelTemp, float oilTemp) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn110 = spn_check.isSpnEnabled(j1939_bus_config, 110);
    bool spn174 = spn_check.isSpnEnabled(j1939_bus_config, 174);
    bool spn175 = spn_check.isSpnEnabled(j1939_bus_config, 175);
    if (spn110) {
        buf[0] = j1939_encode.temp8bit(coolantTemp);
    }
    if (spn174) {
        buf[1] = j1939_encode.temp8bit(fuelTemp);
    }
    if (spn175) {
        uint16_t encoded = j1939_encode.temp16bit(oilTemp);
        buf[2] = ((encoded) & 0xFFU);
        buf[3] = ((encoded >> 8) & 0xFFU);
    }
    j1939_bus_sendMessage(65262, buf);
}

void j1939_bus_sendPgn65263(float fuelPres, float oilPres, float coolantPres) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn94 = spn_check.isSpnEnabled(j1939_bus_config, 94);
    bool spn100 = spn_check.isSpnEnabled(j1939_bus_config, 100);
    bool spn109 = spn_check.isSpnEnabled(j1939_bus_config, 109);
    if (spn94) {
        buf[0] = j1939_encode.pressure4kPa(fuelPres);
    }
    if (spn100) {
        buf[3] = j1939_encode.pressure4kPa(oilPres);
    }
    if (spn109) {
        buf[6] = j1939_encode.pressure2kPa(coolantPres);
    }
    j1939_bus_sendMessage(65263, buf);
}

void j1939_bus_sendPgn65269(float ambientTemp, float airInletTemp, float baroPress) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn108 = spn_check.isSpnEnabled(j1939_bus_config, 108);
    bool spn171 = spn_check.isSpnEnabled(j1939_bus_config, 171);
    bool spn172 = spn_check.isSpnEnabled(j1939_bus_config, 172);
    if (spn108) {
        buf[0] = j1939_encode.barometric(baroPress);
    }
    if (spn171) {
        uint16_t encoded = j1939_encode.temp16bit(ambientTemp);
        buf[3] = ((encoded) & 0xFFU);
        buf[4] = ((encoded >> 8) & 0xFFU);
    }
    if (spn172) {
        buf[5] = j1939_encode.temp8bit(airInletTemp);
    }
    j1939_bus_sendMessage(65269, buf);
}

void j1939_bus_sendPgn65270(float airInletPres, float airInletTemp, float egtTemp, float boostPres) {
    uint8_t buf[8] = {0};
    j1939_bus_fillBuffer(buf);
    bool spn102 = spn_check.isSpnEnabled(j1939_bus_config, 102);
    bool spn105 = spn_check.isSpnEnabled(j1939_bus_config, 105);
    bool spn106 = spn_check.isSpnEnabled(j1939_bus_config, 106);
    bool spn173 = spn_check.isSpnEnabled(j1939_bus_config, 173);
    if (spn102) {
        buf[1] = j1939_encode.pressure2kPa(boostPres);
    }
    if (spn105) {
        buf[2] = j1939_encode.temp8bit(airInletTemp);
    }
    if (spn106) {
        buf[3] = j1939_encode.pressure2kPa(airInletPres);
    }
    if (spn173) {
        uint16_t encoded = j1939_encode.temp16bit(egtTemp);
        buf[5] = ((encoded) & 0xFFU);
        buf[6] = ((encoded >> 8) & 0xFFU);
    }
    j1939_bus_sendMessage(65270, buf);
}
