#ifndef J1939_DECODE_H
#define J1939_DECODE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t j1939_decode_getCommand(const uint8_t data[8]);
uint16_t j1939_decode_getSpn(const uint8_t data[8]);
bool j1939_decode_getEnable(const uint8_t data[8]);
uint8_t j1939_decode_getInput(const uint8_t data[8]);
uint8_t j1939_decode_getNtcInput(const uint8_t data[8]);
uint8_t j1939_decode_getNtcParam(const uint8_t data[8]);
uint8_t j1939_decode_getPressureInput(const uint8_t data[8]);
uint16_t j1939_decode_getMaxPressure(const uint8_t data[8]);
uint8_t j1939_decode_getTcType(const uint8_t data[8]);
uint8_t j1939_decode_getQueryType(const uint8_t data[8]);
uint8_t j1939_decode_getSubQuery(const uint8_t data[8]);
uint8_t j1939_decode_getPresetInput(const uint8_t data[8]);
uint8_t j1939_decode_getPresetId(const uint8_t data[8]);
bool j1939_decode_isValidEnableCmd(uint8_t len);
bool j1939_decode_isValidNtcParamCmd(uint8_t len);
bool j1939_decode_isValidPressureRangeCmd(uint8_t len);

#ifdef __cplusplus
}
#endif

#endif /* J1939_DECODE_H */
