/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "j1939_decode.h"

// J1939 Message Decoding Functions
// Parses incoming J1939 command data from CAN bus messages
// Tests array access and byte manipulation patterns
#include <stdint.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: j1939_decode */

uint8_t j1939_decode_getCommand(const uint8_t data[8]) {
    return data[0];
}

uint16_t j1939_decode_getSpn(const uint8_t data[8]) {
    uint16_t high = data[1];
    uint16_t low = data[2];
    uint16_t spn = (high << 8) | low;
    return spn;
}

bool j1939_decode_getEnable(const uint8_t data[8]) {
    if (data[3] != 0) {
        return true;
    }
    return false;
}

uint8_t j1939_decode_getInput(const uint8_t data[8]) {
    return data[4];
}

uint8_t j1939_decode_getNtcInput(const uint8_t data[8]) {
    return data[1];
}

uint8_t j1939_decode_getNtcParam(const uint8_t data[8]) {
    return data[2];
}

uint8_t j1939_decode_getPressureInput(const uint8_t data[8]) {
    return data[1];
}

uint16_t j1939_decode_getMaxPressure(const uint8_t data[8]) {
    uint16_t high = data[2];
    uint16_t low = data[3];
    uint16_t pressure = (high << 8) | low;
    return pressure;
}

uint8_t j1939_decode_getTcType(const uint8_t data[8]) {
    return data[1];
}

uint8_t j1939_decode_getQueryType(const uint8_t data[8]) {
    return data[1];
}

uint8_t j1939_decode_getSubQuery(const uint8_t data[8]) {
    return data[2];
}

uint8_t j1939_decode_getPresetInput(const uint8_t data[8]) {
    return data[1];
}

uint8_t j1939_decode_getPresetId(const uint8_t data[8]) {
    return data[2];
}

bool j1939_decode_isValidEnableCmd(uint8_t len) {
    if (len >= 5) {
        return true;
    }
    return false;
}

bool j1939_decode_isValidNtcParamCmd(uint8_t len) {
    if (len >= 7) {
        return true;
    }
    return false;
}

bool j1939_decode_isValidPressureRangeCmd(uint8_t len) {
    if (len >= 4) {
        return true;
    }
    return false;
}
