/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Display/J1939Decode.h"

// J1939 Message Decoding Functions
// Parses incoming J1939 command data from CAN bus messages
// Tests array access and byte manipulation patterns
#include <stdint.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: J1939Decode */

uint8_t J1939Decode_getCommand(const uint8_t data[8]) {
    return data[0];
}

uint16_t J1939Decode_getSpn(const uint8_t data[8]) {
    uint16_t high = data[1];
    uint16_t low = data[2];
    uint16_t spn = (high << 8) | low;
    return spn;
}

bool J1939Decode_getEnable(const uint8_t data[8]) {
    if (data[3] != 0) {
        return true;
    }
    return false;
}

uint8_t J1939Decode_getInput(const uint8_t data[8]) {
    return data[4];
}

uint8_t J1939Decode_getNtcInput(const uint8_t data[8]) {
    return data[1];
}

uint8_t J1939Decode_getNtcParam(const uint8_t data[8]) {
    return data[2];
}

uint8_t J1939Decode_getPressureInput(const uint8_t data[8]) {
    return data[1];
}

uint16_t J1939Decode_getMaxPressure(const uint8_t data[8]) {
    uint16_t high = data[2];
    uint16_t low = data[3];
    uint16_t pressure = (high << 8) | low;
    return pressure;
}

uint8_t J1939Decode_getTcType(const uint8_t data[8]) {
    return data[1];
}

uint8_t J1939Decode_getQueryType(const uint8_t data[8]) {
    return data[1];
}

uint8_t J1939Decode_getSubQuery(const uint8_t data[8]) {
    return data[2];
}

uint8_t J1939Decode_getPresetInput(const uint8_t data[8]) {
    return data[1];
}

uint8_t J1939Decode_getPresetId(const uint8_t data[8]) {
    return data[2];
}

bool J1939Decode_isValidEnableCmd(uint8_t len) {
    if (len >= 5) {
        return true;
    }
    return false;
}

bool J1939Decode_isValidNtcParamCmd(uint8_t len) {
    if (len >= 7) {
        return true;
    }
    return false;
}

bool J1939Decode_isValidPressureRangeCmd(uint8_t len) {
    if (len >= 4) {
        return true;
    }
    return false;
}
