#ifndef J1939DECODE_H
#define J1939DECODE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t J1939Decode_getCommand(const uint8_t data[8]);
uint16_t J1939Decode_getSpn(const uint8_t data[8]);
bool J1939Decode_getEnable(const uint8_t data[8]);
uint8_t J1939Decode_getInput(const uint8_t data[8]);
uint8_t J1939Decode_getNtcInput(const uint8_t data[8]);
uint8_t J1939Decode_getNtcParam(const uint8_t data[8]);
uint8_t J1939Decode_getPressureInput(const uint8_t data[8]);
uint16_t J1939Decode_getMaxPressure(const uint8_t data[8]);
uint8_t J1939Decode_getTcType(const uint8_t data[8]);
uint8_t J1939Decode_getQueryType(const uint8_t data[8]);
uint8_t J1939Decode_getSubQuery(const uint8_t data[8]);
uint8_t J1939Decode_getPresetInput(const uint8_t data[8]);
uint8_t J1939Decode_getPresetId(const uint8_t data[8]);
bool J1939Decode_isValidEnableCmd(uint8_t len);
bool J1939Decode_isValidNtcParamCmd(uint8_t len);
bool J1939Decode_isValidPressureRangeCmd(uint8_t len);

#ifdef __cplusplus
}
#endif

#endif /* J1939DECODE_H */
