/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "J1939Encode.h"

#include <stdint.h>

// J1939 SPN Encoding Functions
// Converts sensor values to J1939 protocol format per SAE J1939-71
/* Scope: J1939Encode */

uint16_t J1939Encode_temp16bit(float temperatureC) {
    float offset = temperatureC + 273.0;
    float scaled = offset / 0.03125;
    return static_cast<uint16_t>(scaled);
}

uint8_t J1939Encode_temp8bit(float temperatureC) {
    float offset = temperatureC + 40.0;
    return static_cast<uint8_t>(offset);
}

uint8_t J1939Encode_humidity(float humidityPercent) {
    float scaled = humidityPercent / 0.4;
    return static_cast<uint8_t>(scaled);
}

uint16_t J1939Encode_boost16bit(float pressurekPa) {
    float scaled = pressurekPa / 0.125;
    return static_cast<uint16_t>(scaled);
}

uint8_t J1939Encode_pressure4kPa(float pressurekPa) {
    float scaled = pressurekPa / 4.0;
    return static_cast<uint8_t>(scaled);
}

uint8_t J1939Encode_pressure2kPa(float pressurekPa) {
    float scaled = pressurekPa / 2.0;
    return static_cast<uint8_t>(scaled);
}

uint16_t J1939Encode_pressure16bit(float pressurekPa) {
    float scaled = pressurekPa / 0.5;
    return static_cast<uint16_t>(scaled);
}

uint8_t J1939Encode_barometric(float pressurekPa) {
    float scaled = pressurekPa / 0.5;
    return static_cast<uint8_t>(scaled);
}

uint8_t J1939Encode_lowByte(uint16_t value) {
    return static_cast<uint8_t>((value & 0xFF));
}

uint8_t J1939Encode_highByte(uint16_t value) {
    return static_cast<uint8_t>(((value >> 8) & 0xFF));
}
