#ifndef SENSOR_CONVERT_H
#define SENSOR_CONVERT_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
struct TTempInputConfig;
struct TPressureInputConfig;

/* Function prototypes */
float sensor_convert_clampPositive(float x);
float sensor_convert_defaultAtmosphericPressure(void);
float sensor_convert_ntcTemperature(float voltage, const TTempInputConfig* cfg);
float sensor_convert_pressure(float voltage, const TPressureInputConfig* cfg, float atmosphericPressurekPa);

#ifdef __cplusplus
}
#endif

#endif /* SENSOR_CONVERT_H */
