/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "sensor_convert.h"

// Sensor Conversion Functions
// Physics calculations for NTC thermistors and pressure sensors
#include <math.h>
#include "AppConfig.h"

#include <stdint.h>

/* Scope: sensor_convert */

float sensor_convert_clampPositive(float x) {
    if (x < 0.0) {
        return 0.0;
    }
    return x;
}

float sensor_convert_defaultAtmosphericPressure(void) {
    return 101.325;
}

float sensor_convert_ntcTemperature(float voltage, const TTempInputConfig* cfg) {
    if (voltage <= 0.0) {
        return -273.15;
    }
    if (voltage >= 5.0) {
        return -273.15;
    }
    float r_ntc = cfg->resistorValue * voltage / (5.0 - voltage);
    float lnR = log(r_ntc);
    float lnR3 = lnR * lnR * lnR;
    float invT = cfg->coeffA + cfg->coeffB * lnR + cfg->coeffC * lnR3;
    float tempK = 1.0 / invT;
    return tempK - 273.15;
}

float sensor_convert_pressure(float voltage, const TPressureInputConfig* cfg, float atmosphericPressurekPa) {
    if (voltage < 0.5) {
        return 0.0;
    }
    float clampedVoltage = voltage;
    if (clampedVoltage > 4.5) {
        clampedVoltage = 4.5;
    }
    float ratio = (clampedVoltage - 0.5) / (4.5 - 0.5);
    if (cfg->pressureType == PRESSURE_TYPE_PSIA) {
        if (cfg->maxPressure > 20000) {
            float maxBar = static_cast<float>((cfg->maxPressure - 20000));
            float bar = ratio * maxBar;
            return sensor_convert_clampPositive(bar * 100.0);
        } else {
            float maxkPa = static_cast<float>(cfg->maxPressure);
            return sensor_convert_clampPositive(ratio * maxkPa);
        }
    } else {
        float maxPsi = static_cast<float>(cfg->maxPressure);
        float psi = ratio * maxPsi;
        float gaugekPa = psi * 6.894757;
        return sensor_convert_clampPositive(gaugekPa + atmosphericPressurekPa);
    }
}
