#ifndef SPN_INFO_H
#define SPN_INFO_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t spn_info_IDX_OIL_TEMP;
extern const uint8_t spn_info_IDX_COOLANT_TEMP;
extern const uint8_t spn_info_IDX_FUEL_TEMP;
extern const uint8_t spn_info_IDX_BOOST_TEMP;
extern const uint8_t spn_info_IDX_CAC_INLET_TEMP;
extern const uint8_t spn_info_IDX_XFER_PIPE_TEMP;
extern const uint8_t spn_info_IDX_AIR_INLET_TEMP4;
extern const uint8_t spn_info_IDX_AIR_INLET_TEMP;
extern const uint8_t spn_info_IDX_ENG_BAY_TEMP;
extern const uint8_t spn_info_IDX_OIL_PRES;
extern const uint8_t spn_info_IDX_COOLANT_PRES;
extern const uint8_t spn_info_IDX_FUEL_PRES;
extern const uint8_t spn_info_IDX_BOOST_PRES;
extern const uint8_t spn_info_IDX_AIR_INLET_PRES;
extern const uint8_t spn_info_IDX_CAC_INLET_PRES;
extern const uint8_t spn_info_IDX_XFER_PIPE_PRES;
extern const uint8_t spn_info_IDX_EGT;
extern const uint8_t spn_info_IDX_AMBIENT_TEMP;
extern const uint8_t spn_info_IDX_BARO_PRES;
extern const uint8_t spn_info_IDX_HUMIDITY;
extern const uint8_t spn_info_IDX_UNKNOWN;

/* Function prototypes */
uint8_t spn_info_getIndex(uint16_t spn);
bool spn_info_isKnown(uint16_t spn);
uint16_t spn_info_getHiResSpn(uint16_t spn);
bool spn_info_hasHiRes(uint16_t spn);
bool spn_info_isHiRes(uint16_t spn);
uint16_t spn_info_getBaseSpn(uint16_t spn);
uint8_t spn_info_knownCount(void);

#ifdef __cplusplus
}
#endif

#endif /* SPN_INFO_H */
