/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "SpnCheck.h"

// SPN Enable Checking Functions
// Determines if a given SPN is enabled in the configuration
#include "../AppConfig.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: SpnCheck */

bool SpnCheck_isTempSpnEnabled(const AppConfig* cfg, uint16_t spn) {
    for (uint8_t i = 0; i < TEMP_INPUT_COUNT; i += 1) {
        if (cfg->tempInputs[i].assignedSpn == spn) {
            return true;
        }
    }
    return false;
}

bool SpnCheck_isPressureSpnEnabled(const AppConfig* cfg, uint16_t spn) {
    for (uint8_t i = 0; i < PRESSURE_INPUT_COUNT; i += 1) {
        if (cfg->pressureInputs[i].assignedSpn == spn) {
            return true;
        }
    }
    return false;
}

bool SpnCheck_isSpnEnabled(const AppConfig* cfg, uint16_t spn) {
    bool tempEnabled = SpnCheck_isTempSpnEnabled(cfg, spn);
    if (tempEnabled) {
        return true;
    }
    bool pressureEnabled = SpnCheck_isPressureSpnEnabled(cfg, spn);
    if (pressureEnabled) {
        return true;
    }
    if (spn == 173) {
        if (cfg->egtEnabled) {
            return true;
        }
    }
    if (spn == 171) {
        if (cfg->bme280Enabled) {
            return true;
        }
    }
    if (spn == 108) {
        if (cfg->bme280Enabled) {
            return true;
        }
    }
    if (spn == 354) {
        if (cfg->bme280Enabled) {
            return true;
        }
    }
    if (spn == 1637) {
        bool coolantEnabled = SpnCheck_isTempSpnEnabled(cfg, 110);
        if (coolantEnabled) {
            return true;
        }
    }
    if (spn == 1363) {
        bool intakeEnabled = SpnCheck_isTempSpnEnabled(cfg, 105);
        if (intakeEnabled) {
            return true;
        }
    }
    return false;
}
