/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "SpnCategory.h"

// SPN Category Lookup Functions
// Maps SPNs to their sensor category (temperature, pressure, EGT, BME280)
// Also provides hi-res SPN mapping for dual-resolution sensors
#include <AppConfig.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: SpnCategory */

ESpnCategory SpnCategory_getCategory(uint16_t spn) {
    if (spn == 175) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 110) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 174) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 105) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 1131) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 1132) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 1133) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 172) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 441) {
        return ESpnCategory_SPN_CAT_TEMPERATURE;
    }
    if (spn == 100) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 109) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 94) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 102) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 106) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 1127) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 1128) {
        return ESpnCategory_SPN_CAT_PRESSURE;
    }
    if (spn == 173) {
        return ESpnCategory_SPN_CAT_EGT;
    }
    if (spn == 171) {
        return ESpnCategory_SPN_CAT_BME280;
    }
    if (spn == 108) {
        return ESpnCategory_SPN_CAT_BME280;
    }
    if (spn == 354) {
        return ESpnCategory_SPN_CAT_BME280;
    }
    return ESpnCategory_SPN_CAT_UNKNOWN;
}

bool SpnCategory_isValidSpn(uint16_t spn) {
    ESpnCategory cat = SpnCategory_getCategory(spn);
    if (cat == ESpnCategory_SPN_CAT_UNKNOWN) {
        return false;
    }
    return true;
}

uint16_t SpnCategory_getHiResSpn(uint16_t spn) {
    if (spn == 110) {
        return 1637;
    }
    if (spn == 105) {
        return 1363;
    }
    return 0;
}

bool SpnCategory_hasHiResVariant(uint16_t spn) {
    uint16_t hiRes = SpnCategory_getHiResSpn(spn);
    if (hiRes == 0) {
        return false;
    }
    return true;
}

bool SpnCategory_isTemperatureCategory(ESpnCategory category) {
    if (category == ESpnCategory_SPN_CAT_TEMPERATURE) {
        return true;
    }
    return false;
}

bool SpnCategory_isPressureCategory(ESpnCategory category) {
    if (category == ESpnCategory_SPN_CAT_PRESSURE) {
        return true;
    }
    return false;
}
