/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "SpnInfo.h"

// SPN Information Lookup
// Provides SPN metadata without string handling
// String labels are kept in C++ code, this module returns indices
#include <stdint.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: SpnInfo */
const uint8_t SpnInfo_IDX_OIL_TEMP = 0;
const uint8_t SpnInfo_IDX_COOLANT_TEMP = 1;
const uint8_t SpnInfo_IDX_FUEL_TEMP = 2;
const uint8_t SpnInfo_IDX_BOOST_TEMP = 3;
const uint8_t SpnInfo_IDX_CAC_INLET_TEMP = 4;
const uint8_t SpnInfo_IDX_XFER_PIPE_TEMP = 5;
const uint8_t SpnInfo_IDX_AIR_INLET_TEMP4 = 6;
const uint8_t SpnInfo_IDX_AIR_INLET_TEMP = 7;
const uint8_t SpnInfo_IDX_ENG_BAY_TEMP = 8;
const uint8_t SpnInfo_IDX_OIL_PRES = 9;
const uint8_t SpnInfo_IDX_COOLANT_PRES = 10;
const uint8_t SpnInfo_IDX_FUEL_PRES = 11;
const uint8_t SpnInfo_IDX_BOOST_PRES = 12;
const uint8_t SpnInfo_IDX_AIR_INLET_PRES = 13;
const uint8_t SpnInfo_IDX_CAC_INLET_PRES = 14;
const uint8_t SpnInfo_IDX_XFER_PIPE_PRES = 15;
const uint8_t SpnInfo_IDX_EGT = 16;
const uint8_t SpnInfo_IDX_AMBIENT_TEMP = 17;
const uint8_t SpnInfo_IDX_BARO_PRES = 18;
const uint8_t SpnInfo_IDX_HUMIDITY = 19;
const uint8_t SpnInfo_IDX_UNKNOWN = 255;

uint8_t SpnInfo_getIndex(uint16_t spn) {
    if (spn == 175) {
        return SpnInfo_IDX_OIL_TEMP;
    }
    if (spn == 110) {
        return SpnInfo_IDX_COOLANT_TEMP;
    }
    if (spn == 1637) {
        return SpnInfo_IDX_COOLANT_TEMP;
    }
    if (spn == 174) {
        return SpnInfo_IDX_FUEL_TEMP;
    }
    if (spn == 105) {
        return SpnInfo_IDX_BOOST_TEMP;
    }
    if (spn == 1363) {
        return SpnInfo_IDX_BOOST_TEMP;
    }
    if (spn == 1131) {
        return SpnInfo_IDX_CAC_INLET_TEMP;
    }
    if (spn == 1132) {
        return SpnInfo_IDX_XFER_PIPE_TEMP;
    }
    if (spn == 1133) {
        return SpnInfo_IDX_AIR_INLET_TEMP4;
    }
    if (spn == 172) {
        return SpnInfo_IDX_AIR_INLET_TEMP;
    }
    if (spn == 441) {
        return SpnInfo_IDX_ENG_BAY_TEMP;
    }
    if (spn == 100) {
        return SpnInfo_IDX_OIL_PRES;
    }
    if (spn == 109) {
        return SpnInfo_IDX_COOLANT_PRES;
    }
    if (spn == 94) {
        return SpnInfo_IDX_FUEL_PRES;
    }
    if (spn == 102) {
        return SpnInfo_IDX_BOOST_PRES;
    }
    if (spn == 106) {
        return SpnInfo_IDX_AIR_INLET_PRES;
    }
    if (spn == 1127) {
        return SpnInfo_IDX_CAC_INLET_PRES;
    }
    if (spn == 1128) {
        return SpnInfo_IDX_XFER_PIPE_PRES;
    }
    if (spn == 173) {
        return SpnInfo_IDX_EGT;
    }
    if (spn == 171) {
        return SpnInfo_IDX_AMBIENT_TEMP;
    }
    if (spn == 108) {
        return SpnInfo_IDX_BARO_PRES;
    }
    if (spn == 354) {
        return SpnInfo_IDX_HUMIDITY;
    }
    return SpnInfo_IDX_UNKNOWN;
}

bool SpnInfo_isKnown(uint16_t spn) {
    uint8_t idx = SpnInfo_getIndex(spn);
    if (idx == SpnInfo_IDX_UNKNOWN) {
        return false;
    }
    return true;
}

uint16_t SpnInfo_getHiResSpn(uint16_t spn) {
    if (spn == 110) {
        return 1637;
    }
    if (spn == 105) {
        return 1363;
    }
    return 0;
}

bool SpnInfo_hasHiRes(uint16_t spn) {
    uint16_t hiRes = SpnInfo_getHiResSpn(spn);
    if (hiRes == 0) {
        return false;
    }
    return true;
}

bool SpnInfo_isHiRes(uint16_t spn) {
    if (spn == 1637) {
        return true;
    }
    if (spn == 1363) {
        return true;
    }
    return false;
}

uint16_t SpnInfo_getBaseSpn(uint16_t spn) {
    if (spn == 1637) {
        return 110;
    }
    if (spn == 1363) {
        return 105;
    }
    return spn;
}

uint8_t SpnInfo_knownCount(void) {
    return 20;
}
