#ifndef SPNINFO_H
#define SPNINFO_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t SpnInfo_IDX_OIL_TEMP;
extern const uint8_t SpnInfo_IDX_COOLANT_TEMP;
extern const uint8_t SpnInfo_IDX_FUEL_TEMP;
extern const uint8_t SpnInfo_IDX_BOOST_TEMP;
extern const uint8_t SpnInfo_IDX_CAC_INLET_TEMP;
extern const uint8_t SpnInfo_IDX_XFER_PIPE_TEMP;
extern const uint8_t SpnInfo_IDX_AIR_INLET_TEMP4;
extern const uint8_t SpnInfo_IDX_AIR_INLET_TEMP;
extern const uint8_t SpnInfo_IDX_ENG_BAY_TEMP;
extern const uint8_t SpnInfo_IDX_OIL_PRES;
extern const uint8_t SpnInfo_IDX_COOLANT_PRES;
extern const uint8_t SpnInfo_IDX_FUEL_PRES;
extern const uint8_t SpnInfo_IDX_BOOST_PRES;
extern const uint8_t SpnInfo_IDX_AIR_INLET_PRES;
extern const uint8_t SpnInfo_IDX_CAC_INLET_PRES;
extern const uint8_t SpnInfo_IDX_XFER_PIPE_PRES;
extern const uint8_t SpnInfo_IDX_EGT;
extern const uint8_t SpnInfo_IDX_AMBIENT_TEMP;
extern const uint8_t SpnInfo_IDX_BARO_PRES;
extern const uint8_t SpnInfo_IDX_HUMIDITY;
extern const uint8_t SpnInfo_IDX_UNKNOWN;

/* Function prototypes */
uint8_t SpnInfo_getIndex(uint16_t spn);
bool SpnInfo_isKnown(uint16_t spn);
uint16_t SpnInfo_getHiResSpn(uint16_t spn);
bool SpnInfo_hasHiRes(uint16_t spn);
bool SpnInfo_isHiRes(uint16_t spn);
uint16_t SpnInfo_getBaseSpn(uint16_t spn);
uint8_t SpnInfo_knownCount(void);

#ifdef __cplusplus
}
#endif

#endif /* SPNINFO_H */
