/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "ValueName.h"

// Human-readable names for EValueId values
// Data-driven lookup table indexed by (u8)id
#include <Arduino.h>
#include <Data/types/EValueId.h>

#include <stdint.h>

extern const TValueInfo VALUE_NAMES[EValueId_VALUE_ID_COUNT] = {(TValueInfo){ .id = EValueId_AMBIENT_PRES, .name = "Ambient Pres" }, (TValueInfo){ .id = EValueId_AMBIENT_TEMP, .name = "Ambient Temp" }, (TValueInfo){ .id = EValueId_AMBIENT_HUMIDITY, .name = "Ambient Humidity" }, (TValueInfo){ .id = EValueId_TURBO1_COMP_INLET_PRES, .name = "Turbo Comp In Pres" }, (TValueInfo){ .id = EValueId_TURBO1_COMP_INLET_TEMP, .name = "Turbo Comp In Temp" }, (TValueInfo){ .id = EValueId_TURBO1_COMP_OUTLET_PRES, .name = "Turbo Comp Out Pres" }, (TValueInfo){ .id = EValueId_TURBO1_COMP_OUTLET_TEMP, .name = "Turbo Comp Out Temp" }, (TValueInfo){ .id = EValueId_TURBO1_TURB_INLET_TEMP, .name = "EGT" }, (TValueInfo){ .id = EValueId_CAC1_INLET_PRES, .name = "CAC Inlet Pres" }, (TValueInfo){ .id = EValueId_CAC1_INLET_TEMP, .name = "CAC Inlet Temp" }, (TValueInfo){ .id = EValueId_CAC1_OUTLET_PRES, .name = "CAC Outlet Pres" }, (TValueInfo){ .id = EValueId_CAC1_OUTLET_TEMP, .name = "CAC Outlet Temp" }, (TValueInfo){ .id = EValueId_MANIFOLD1_ABS_PRES, .name = "Manifold Pres" }, (TValueInfo){ .id = EValueId_MANIFOLD1_TEMP, .name = "Manifold Temp" }, (TValueInfo){ .id = EValueId_OIL_PRES, .name = "Oil Pres" }, (TValueInfo){ .id = EValueId_OIL_TEMP, .name = "Oil Temp" }, (TValueInfo){ .id = EValueId_COOLANT_PRES, .name = "Coolant Pres" }, (TValueInfo){ .id = EValueId_COOLANT_TEMP, .name = "Coolant Temp" }, (TValueInfo){ .id = EValueId_FUEL_PRES, .name = "Fuel Pres" }, (TValueInfo){ .id = EValueId_FUEL_TEMP, .name = "Fuel Temp" }, (TValueInfo){ .id = EValueId_ENGINE_BAY_TEMP, .name = "Engine Bay Temp" }};

/* Scope: ValueName */

void ValueName_print(EValueId id) {
    uint8_t idx = static_cast<uint8_t>(id);
    if (idx < EValueId_VALUE_ID_COUNT) {
        Serial.print(VALUE_NAMES[idx].name);
    } else {
        Serial.print("Unknown");
    }
}
