#ifndef SENSORPROCESSOR_H
#define SENSORPROCESSOR_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;
typedef struct AppData AppData;

/* Function prototypes */
void SensorProcessor_initialize(const AppConfig* cfg);
void SensorProcessor_processAllInputs(AppData* appData);

#ifdef __cplusplus
}
#endif

#endif /* SENSORPROCESSOR_H */
