#ifndef SERIALCOMMANDHANDLER_H
#define SERIALCOMMANDHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Display/AppData.h>
#include <Data/ConfigStorage/ConfigStorage.h>
#include <Data/MAX31856Manager/MAX31856Manager.h>
#include <Data/BME280Manager/BME280Manager.h>
#include <Domain/CommandHandler/CommandHandler.h>
#include <Domain/CommandHandler/TCommandResult.h>
#include <Display/SpnCategory.h>
#include <Display/SpnInfo.h>
#include <Display/FaultDecode.h>
#include <Display/J1939Bus.h>
#include <Display/J1939Encode.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;
typedef struct AppData AppData;
typedef struct SeaDash_Parse_ParseResult SeaDash_Parse_ParseResult;

/* External variables */
extern const char SPN_LABELS[20][33];
extern char cmdBuffer[129];
extern uint8_t cmdIndex;
extern SeaDash_Parse_ParseResult parsed;

/* Function prototypes */
void SerialCommandHandler_initialize(void);
void SerialCommandHandler_update(const AppConfig* config, const AppData* appData);

#ifdef __cplusplus
}
#endif

#endif /* SERIALCOMMANDHANDLER_H */
