#ifndef BME280MANAGER_H
#define BME280MANAGER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;

/* Function prototypes */
void BME280Manager_initialize(const AppConfig* config);
bool BME280Manager_update(void);
float BME280Manager_getTemperatureC(void);
float BME280Manager_getHumidity(void);
float BME280Manager_getPressurekPa(void);
bool BME280Manager_isEnabled(void);

#ifdef __cplusplus
}
#endif

#endif /* BME280MANAGER_H */
