#ifndef TADCREADING_H
#define TADCREADING_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TAdcReading {
    int16_t rawValue;
    uint32_t timestamp;
    bool valid;
} TAdcReading;

#ifdef __cplusplus
}
#endif

#endif /* TADCREADING_H */
