#ifndef TPGNCONFIG_H
#define TPGNCONFIG_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TPgnConfig {
    uint16_t pgn;
    uint16_t intervalMs;
    uint8_t dataLength;
    uint8_t priority;
} TPgnConfig;

#ifdef __cplusplus
}
#endif

#endif /* TPGNCONFIG_H */
