#ifndef TSPNCONFIG_H
#define TSPNCONFIG_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "EValueId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TSpnConfig {
    uint16_t spn;
    uint16_t pgn;
    uint8_t bytePos;
    uint8_t dataLength;
    float resolution;
    float offset;
    EValueId source;
} TSpnConfig;

#ifdef __cplusplus
}
#endif

#endif /* TSPNCONFIG_H */
