#ifndef APPCONFIG_H
#define APPCONFIG_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EThermocoupleType_TC_TYPE_B = 0,
    EThermocoupleType_TC_TYPE_E = 1,
    EThermocoupleType_TC_TYPE_J = 2,
    EThermocoupleType_TC_TYPE_K = 3,
    EThermocoupleType_TC_TYPE_N = 4,
    EThermocoupleType_TC_TYPE_R = 5,
    EThermocoupleType_TC_TYPE_S = 6,
    EThermocoupleType_TC_TYPE_T = 7
} EThermocoupleType;
typedef enum {
    ENtcPreset_NTC_PRESET_AEM = 0,
    ENtcPreset_NTC_PRESET_BOSCH = 1,
    ENtcPreset_NTC_PRESET_GM = 2
} ENtcPreset;
typedef enum {
    EPressureType_PRESSURE_TYPE_PSIA = 0,
    EPressureType_PRESSURE_TYPE_PSIG = 1
} EPressureType;
typedef enum {
    EPressurePreset_PRESSURE_PRESET_1_BAR = 0,
    EPressurePreset_PRESSURE_PRESET_1_5_BAR = 1,
    EPressurePreset_PRESSURE_PRESET_2_BAR = 2,
    EPressurePreset_PRESSURE_PRESET_2_5_BAR = 3,
    EPressurePreset_PRESSURE_PRESET_3_BAR = 4,
    EPressurePreset_PRESSURE_PRESET_4_BAR = 5,
    EPressurePreset_PRESSURE_PRESET_5_BAR = 6,
    EPressurePreset_PRESSURE_PRESET_7_BAR = 7,
    EPressurePreset_PRESSURE_PRESET_10_BAR = 8,
    EPressurePreset_PRESSURE_PRESET_50_BAR = 9,
    EPressurePreset_PRESSURE_PRESET_100_BAR = 10,
    EPressurePreset_PRESSURE_PRESET_150_BAR = 11,
    EPressurePreset_PRESSURE_PRESET_200_BAR = 12,
    EPressurePreset_PRESSURE_PRESET_1000_BAR = 13,
    EPressurePreset_PRESSURE_PRESET_2000_BAR = 14,
    EPressurePreset_PRESSURE_PRESET_3000_BAR = 15,
    EPressurePreset_PRESSURE_PRESET_15_PSIG = 20,
    EPressurePreset_PRESSURE_PRESET_30_PSIG = 21,
    EPressurePreset_PRESSURE_PRESET_50_PSIG = 22,
    EPressurePreset_PRESSURE_PRESET_100_PSIG = 23,
    EPressurePreset_PRESSURE_PRESET_150_PSIG = 24,
    EPressurePreset_PRESSURE_PRESET_200_PSIG = 25,
    EPressurePreset_PRESSURE_PRESET_250_PSIG = 26,
    EPressurePreset_PRESSURE_PRESET_300_PSIG = 27,
    EPressurePreset_PRESSURE_PRESET_350_PSIG = 28,
    EPressurePreset_PRESSURE_PRESET_400_PSIG = 29,
    EPressurePreset_PRESSURE_PRESET_500_PSIG = 30
} EPressurePreset;
typedef enum {
    ESpnCategory_SPN_CAT_TEMPERATURE = 0,
    ESpnCategory_SPN_CAT_PRESSURE = 1,
    ESpnCategory_SPN_CAT_EGT = 2,
    ESpnCategory_SPN_CAT_BME280 = 3,
    ESpnCategory_SPN_CAT_UNKNOWN = 4
} ESpnCategory;

/* Struct definitions */
typedef struct TTempInputConfig {
    uint16_t assignedSpn;
    float coeffA;
    float coeffB;
    float coeffC;
    float resistorValue;
} TTempInputConfig;
typedef struct TPressureInputConfig {
    uint16_t assignedSpn;
    uint16_t maxPressure;
    EPressureType pressureType;
    uint8_t reserved;
} TPressureInputConfig;
typedef struct THardwareMapping {
    uint8_t adsDevice;
    uint8_t adsChannel;
} THardwareMapping;
typedef struct TSpnInfo {
    uint16_t spn;
    ESpnCategory category;
    uint16_t hiResSpn;
} TSpnInfo;
typedef struct AppConfig {
    uint32_t magic;
    uint8_t version;
    uint8_t j1939SourceAddress;
    uint8_t reserved[2];
    TTempInputConfig tempInputs[8];
    TPressureInputConfig pressureInputs[7];
    bool egtEnabled;
    EThermocoupleType thermocoupleType;
    uint8_t tcReserved[2];
    bool bme280Enabled;
    uint8_t bme280Reserved[3];
    uint32_t checksum;
} AppConfig;

/* External variables */
extern const uint32_t CONFIG_MAGIC;
extern const uint8_t CONFIG_VERSION;
extern const uint8_t TEMP_INPUT_COUNT;
extern const uint8_t PRESSURE_INPUT_COUNT;
extern const uint8_t ADS_DEVICE_COUNT;
extern const float AEM_TEMP_COEFF_A;
extern const float AEM_TEMP_COEFF_B;
extern const float AEM_TEMP_COEFF_C;
extern const float AEM_TEMP_RESISTOR;
extern const float BOSCH_TEMP_COEFF_A;
extern const float BOSCH_TEMP_COEFF_B;
extern const float BOSCH_TEMP_COEFF_C;
extern const float BOSCH_TEMP_RESISTOR;
extern const float GM_TEMP_COEFF_A;
extern const float GM_TEMP_COEFF_B;
extern const float GM_TEMP_COEFF_C;
extern const float GM_TEMP_RESISTOR;
extern const THardwareMapping TEMP_HARDWARE_MAP[8];
extern const THardwareMapping PRESSURE_HARDWARE_MAP[7];
extern const uint8_t ADS_I2C_ADDRESSES[4];
extern const uint8_t ADS_DRDY_PINS[4];
extern const TSpnInfo KNOWN_SPNS[20];
extern const uint8_t KNOWN_SPN_COUNT;

#ifdef __cplusplus
}
#endif

#endif /* APPCONFIG_H */
