#ifndef MAIN_H
#define MAIN_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void setup(void);
void loop(void);

#ifdef __cplusplus
}
#endif

#endif /* MAIN_H */
