/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// AppConfig.cnx - Main configuration types and constants for OSSM
#include <Data/types/EValueId.h>

#include <stdint.h>
#include <stdbool.h>

// Configuration magic number and version
extern const uint32_t CONFIG_MAGIC = 0x4F53534D;

// "OSSM" in ASCII
extern const uint8_t CONFIG_VERSION = 4;

// EValueId-based config (was SPN-based)
// Number of user-facing inputs
extern const uint8_t TEMP_INPUT_COUNT = 8;

extern const uint8_t PRESSURE_INPUT_COUNT = 7;

// ADS1115 device count (internal, fixed)
extern const uint8_t ADS_DEVICE_COUNT = 4;

// Thermocouple types (MAX31856)
typedef enum {
    EThermocoupleType_TC_TYPE_B = 0,
    EThermocoupleType_TC_TYPE_E = 1,
    EThermocoupleType_TC_TYPE_J = 2,
    EThermocoupleType_TC_TYPE_K = 3,
    EThermocoupleType_TC_TYPE_N = 4,
    EThermocoupleType_TC_TYPE_R = 5,
    EThermocoupleType_TC_TYPE_S = 6,
    EThermocoupleType_TC_TYPE_T = 7
} EThermocoupleType;

// NTC Presets
typedef enum {
    ENtcPreset_NTC_PRESET_AEM = 0,
    ENtcPreset_NTC_PRESET_BOSCH = 1,
    ENtcPreset_NTC_PRESET_GM = 2
} ENtcPreset;

// Pressure Type (PSIA = absolute, PSIG = gauge)
typedef enum {
    EPressureType_PRESSURE_TYPE_PSIA = 0,
    EPressureType_PRESSURE_TYPE_PSIG = 1
} EPressureType;

// Pressure Presets
// Bar presets (0-15) are PSIA, PSI presets (20-30) are PSIG
typedef enum {
    EPressurePreset_PRESSURE_PRESET_1_BAR = 0,
    EPressurePreset_PRESSURE_PRESET_1_5_BAR = 1,
    EPressurePreset_PRESSURE_PRESET_2_BAR = 2,
    EPressurePreset_PRESSURE_PRESET_2_5_BAR = 3,
    EPressurePreset_PRESSURE_PRESET_3_BAR = 4,
    EPressurePreset_PRESSURE_PRESET_4_BAR = 5,
    EPressurePreset_PRESSURE_PRESET_5_BAR = 6,
    EPressurePreset_PRESSURE_PRESET_7_BAR = 7,
    EPressurePreset_PRESSURE_PRESET_10_BAR = 8,
    EPressurePreset_PRESSURE_PRESET_50_BAR = 9,
    EPressurePreset_PRESSURE_PRESET_100_BAR = 10,
    EPressurePreset_PRESSURE_PRESET_150_BAR = 11,
    EPressurePreset_PRESSURE_PRESET_200_BAR = 12,
    EPressurePreset_PRESSURE_PRESET_1000_BAR = 13,
    EPressurePreset_PRESSURE_PRESET_2000_BAR = 14,
    EPressurePreset_PRESSURE_PRESET_3000_BAR = 15,
    EPressurePreset_PRESSURE_PRESET_15_PSIG = 20,
    EPressurePreset_PRESSURE_PRESET_30_PSIG = 21,
    EPressurePreset_PRESSURE_PRESET_50_PSIG = 22,
    EPressurePreset_PRESSURE_PRESET_100_PSIG = 23,
    EPressurePreset_PRESSURE_PRESET_150_PSIG = 24,
    EPressurePreset_PRESSURE_PRESET_200_PSIG = 25,
    EPressurePreset_PRESSURE_PRESET_250_PSIG = 26,
    EPressurePreset_PRESSURE_PRESET_300_PSIG = 27,
    EPressurePreset_PRESSURE_PRESET_350_PSIG = 28,
    EPressurePreset_PRESSURE_PRESET_400_PSIG = 29,
    EPressurePreset_PRESSURE_PRESET_500_PSIG = 30
} EPressurePreset;

// Known SPNs and their categories
typedef enum {
    ESpnCategory_SPN_CAT_TEMPERATURE = 0,
    ESpnCategory_SPN_CAT_PRESSURE = 1,
    ESpnCategory_SPN_CAT_EGT = 2,
    ESpnCategory_SPN_CAT_BME280 = 3,
    ESpnCategory_SPN_CAT_UNKNOWN = 4
} ESpnCategory;

// Temperature input configuration (temp1-temp8)
typedef struct TTempInputConfig {
    EValueId assignedValue;
    float coeffA;
    float coeffB;
    float coeffC;
    float resistorValue;
} TTempInputConfig;

// Pressure input configuration (pres1-pres7)
typedef struct TPressureInputConfig {
    EValueId assignedValue;
    uint16_t maxPressure;
    EPressureType pressureType;
    uint8_t reserved;
} TPressureInputConfig;

// Fixed hardware mapping: tempX -> ADS device/channel
// This is internal, not user-configurable
typedef struct THardwareMapping {
    uint8_t adsDevice;
    uint8_t adsChannel;
} THardwareMapping;

// SPN definitions
typedef struct TSpnInfo {
    uint16_t spn;
    ESpnCategory category;
    uint16_t hiResSpn;
} TSpnInfo;

// Main configuration structure (stored in EEPROM)
typedef struct AppConfig {
    uint32_t magic;
    uint8_t version;
    uint8_t j1939SourceAddress;
    uint8_t reserved[2];
    TTempInputConfig tempInputs[8];
    TPressureInputConfig pressureInputs[7];
    bool egtEnabled;
    EThermocoupleType thermocoupleType;
    uint8_t tcReserved[2];
    bool bme280Enabled;
    uint8_t bme280Reserved[3];
    uint32_t checksum;
} AppConfig;

// Global config singleton
AppConfig appConfig = {0};

// Default AEM temperature sensor Steinhart-Hart coefficients
extern const float AEM_TEMP_COEFF_A = 1.485995686e-03;

extern const float AEM_TEMP_COEFF_B = 2.279654266e-04;

extern const float AEM_TEMP_COEFF_C = 1.197578033e-07;

extern const float AEM_TEMP_RESISTOR = 10050.0;

// Bosch NTC coefficients (placeholder - need real values)
extern const float BOSCH_TEMP_COEFF_A = 1.40e-03;

extern const float BOSCH_TEMP_COEFF_B = 2.37e-04;

extern const float BOSCH_TEMP_COEFF_C = 9.90e-08;

extern const float BOSCH_TEMP_RESISTOR = 2490.0;

// GM NTC coefficients (placeholder - need real values)
extern const float GM_TEMP_COEFF_A = 1.29e-03;

extern const float GM_TEMP_COEFF_B = 2.35e-04;

extern const float GM_TEMP_COEFF_C = 9.00e-08;

extern const float GM_TEMP_RESISTOR = 3000.0;

// Temperature input hardware mappings (fixed)
// Index 0 = temp1, Index 7 = temp8
extern const THardwareMapping TEMP_HARDWARE_MAP[8] = {(THardwareMapping){ .adsDevice = 0, .adsChannel = 0 }, (THardwareMapping){ .adsDevice = 0, .adsChannel = 2 }, (THardwareMapping){ .adsDevice = 1, .adsChannel = 0 }, (THardwareMapping){ .adsDevice = 1, .adsChannel = 3 }, (THardwareMapping){ .adsDevice = 2, .adsChannel = 1 }, (THardwareMapping){ .adsDevice = 2, .adsChannel = 2 }, (THardwareMapping){ .adsDevice = 3, .adsChannel = 1 }, (THardwareMapping){ .adsDevice = 3, .adsChannel = 2 }};

// Pressure input hardware mappings (fixed)
// Index 0 = pres1, Index 6 = pres7
extern const THardwareMapping PRESSURE_HARDWARE_MAP[7] = {(THardwareMapping){ .adsDevice = 0, .adsChannel = 1 }, (THardwareMapping){ .adsDevice = 0, .adsChannel = 3 }, (THardwareMapping){ .adsDevice = 2, .adsChannel = 0 }, (THardwareMapping){ .adsDevice = 2, .adsChannel = 3 }, (THardwareMapping){ .adsDevice = 1, .adsChannel = 1 }, (THardwareMapping){ .adsDevice = 1, .adsChannel = 2 }, (THardwareMapping){ .adsDevice = 3, .adsChannel = 0 }};

// ADS1115 device I2C addresses (fixed)
extern const uint8_t ADS_I2C_ADDRESSES[4] = {0x48, 0x49, 0x4A, 0x4B};

// ADS1115 DRDY pins (fixed)
extern const uint8_t ADS_DRDY_PINS[4] = {0, 1, 4, 5};

// D0, D1, D4, D5
// Known SPNs lookup table
extern const TSpnInfo KNOWN_SPNS[20] = {(TSpnInfo){ .spn = 175, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 110, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 1637 }, (TSpnInfo){ .spn = 174, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 105, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 1363 }, (TSpnInfo){ .spn = 1131, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 1132, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 1133, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 172, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 441, .category = ESpnCategory_SPN_CAT_TEMPERATURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 100, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 109, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 94, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 102, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 106, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 1127, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 1128, .category = ESpnCategory_SPN_CAT_PRESSURE, .hiResSpn = 0 }, (TSpnInfo){ .spn = 173, .category = ESpnCategory_SPN_CAT_EGT, .hiResSpn = 0 }, (TSpnInfo){ .spn = 171, .category = ESpnCategory_SPN_CAT_BME280, .hiResSpn = 0 }, (TSpnInfo){ .spn = 108, .category = ESpnCategory_SPN_CAT_BME280, .hiResSpn = 0 }, (TSpnInfo){ .spn = 354, .category = ESpnCategory_SPN_CAT_BME280, .hiResSpn = 0 }};

extern const uint8_t KNOWN_SPN_COUNT = 20;
