#ifndef BYTE_UTILS_H
#define BYTE_UTILS_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint16_t byte_utils_makeU16BE(uint8_t high, uint8_t low);
uint16_t byte_utils_makeU16LE(uint8_t low, uint8_t high);
uint8_t byte_utils_highByte(uint16_t value);
uint8_t byte_utils_lowByte(uint16_t value);
uint32_t byte_utils_makeU32BE(uint8_t b3, uint8_t b2, uint8_t b1, uint8_t b0);
uint32_t byte_utils_makeU32LE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3);
uint8_t byte_utils_byte0(uint32_t value);
uint8_t byte_utils_byte1(uint32_t value);
uint8_t byte_utils_byte2(uint32_t value);
uint8_t byte_utils_byte3(uint32_t value);
bool byte_utils_isBitSet(uint8_t value, uint8_t bit);
uint8_t byte_utils_setBit(uint8_t value, uint8_t bit);
uint8_t byte_utils_clearBit(uint8_t value, uint8_t bit);
uint8_t byte_utils_clampU8(uint8_t value, uint8_t minVal, uint8_t maxVal);
uint16_t byte_utils_clampU16(uint16_t value, uint16_t minVal, uint16_t maxVal);

#ifdef __cplusplus
}
#endif

#endif /* BYTE_UTILS_H */
