#ifndef HARDWARE_MAP_H
#define HARDWARE_MAP_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t TEMP_COUNT;
extern const uint8_t PRES_COUNT;

/* Function prototypes */
uint8_t hardware_map_tempDevice(uint8_t input);
uint8_t hardware_map_tempChannel(uint8_t input);
uint8_t hardware_map_pressureDevice(uint8_t input);
uint8_t hardware_map_pressureChannel(uint8_t input);
uint8_t hardware_map_adsI2cAddress(uint8_t device);
bool hardware_map_isValidTempInput(uint8_t input);
bool hardware_map_isValidPressureInput(uint8_t input);

#ifdef __cplusplus
}
#endif

#endif /* HARDWARE_MAP_H */
