/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "input_valid.h"

// Input Validation Module
// Centralizes all input range checking for commands
// Supports both 1-indexed (user-facing) and 0-indexed (internal) inputs
#include <stdint.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: input_valid */
const uint8_t input_valid_TEMP_COUNT = 8;
const uint8_t input_valid_PRESSURE_COUNT = 7;
const uint8_t input_valid_NTC_PARAM_COUNT = 4;

bool input_valid_isValidTempInput(uint8_t input) {
    if (input < 1) {
        return false;
    }
    if (input > input_valid_TEMP_COUNT) {
        return false;
    }
    return true;
}

bool input_valid_isValidTempIndex(uint8_t index) {
    if (index >= input_valid_TEMP_COUNT) {
        return false;
    }
    return true;
}

uint8_t input_valid_tempInputToIndex(uint8_t input) {
    if (input < 1) {
        return 255;
    }
    if (input > input_valid_TEMP_COUNT) {
        return 255;
    }
    return input - 1;
}

uint8_t input_valid_tempIndexToInput(uint8_t index) {
    if (index >= input_valid_TEMP_COUNT) {
        return 0;
    }
    return index + 1;
}

bool input_valid_isValidPressureInput(uint8_t input) {
    if (input < 1) {
        return false;
    }
    if (input > input_valid_PRESSURE_COUNT) {
        return false;
    }
    return true;
}

bool input_valid_isValidPressureIndex(uint8_t index) {
    if (index >= input_valid_PRESSURE_COUNT) {
        return false;
    }
    return true;
}

uint8_t input_valid_pressureInputToIndex(uint8_t input) {
    if (input < 1) {
        return 255;
    }
    if (input > input_valid_PRESSURE_COUNT) {
        return 255;
    }
    return input - 1;
}

uint8_t input_valid_pressureIndexToInput(uint8_t index) {
    if (index >= input_valid_PRESSURE_COUNT) {
        return 0;
    }
    return index + 1;
}

bool input_valid_isValidNtcParam(uint8_t param) {
    if (param > 3) {
        return false;
    }
    return true;
}

bool input_valid_isValidQueryType(uint8_t queryType) {
    if (queryType == 0) {
        return true;
    }
    if (queryType == 1) {
        return true;
    }
    if (queryType == 2) {
        return true;
    }
    if (queryType == 4) {
        return true;
    }
    return false;
}

bool input_valid_isValidSubQuery(uint8_t subQuery) {
    if (subQuery > 2) {
        return false;
    }
    return true;
}

bool input_valid_isValidJ1939Address(uint8_t address) {
    if (address == 0) {
        return false;
    }
    if (address == 254) {
        return false;
    }
    if (address == 255) {
        return false;
    }
    return true;
}

bool input_valid_isValidAdsDevice(uint8_t device) {
    if (device > 3) {
        return false;
    }
    return true;
}

bool input_valid_isValidAdsChannel(uint8_t channel) {
    if (channel > 3) {
        return false;
    }
    return true;
}
