#ifndef J1939_ENCODE_H
#define J1939_ENCODE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint16_t j1939_encode_temp16bit(float temperatureC);
uint8_t j1939_encode_temp8bit(float temperatureC);
uint8_t j1939_encode_humidity(float humidityPercent);
uint16_t j1939_encode_boost16bit(float pressurekPa);
uint8_t j1939_encode_pressure4kPa(float pressurekPa);
uint8_t j1939_encode_pressure2kPa(float pressurekPa);
uint16_t j1939_encode_pressure16bit(float pressurekPa);
uint8_t j1939_encode_barometric(float pressurekPa);
uint8_t j1939_encode_lowByte(uint16_t value);
uint8_t j1939_encode_highByte(uint16_t value);

#ifdef __cplusplus
}
#endif

#endif /* J1939_ENCODE_H */
