/**
 * Generated by C-Next Transpiler from: main.cnx
 * A safer C for embedded systems
 */

// Main entry point for OSSM
// Delegates to ossm class for setup and loop
#include <Arduino.h>
#include <Domain/ossm.hpp>

void setup(void) {
    Ossm_setup();
}

void loop(void) {
    Ossm_loop();
}
