/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "presets.h"

// Sensor Preset Lookup Tables
// Provides NTC thermistor and pressure sensor preset configurations
#include "AppConfig.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: presets */

float presets_ntcCoeffA(uint8_t preset) {
    float presets_AEM_COEFF_A = 1.485995686e-03;
    float presets_BOSCH_COEFF_A = 1.40e-03;
    float presets_GM_COEFF_A = 1.29e-03;
    if (preset == 0) {
        return presets_AEM_COEFF_A;
    }
    if (preset == 1) {
        return presets_BOSCH_COEFF_A;
    }
    if (preset == 2) {
        return presets_GM_COEFF_A;
    }
    return 0.0;
}

float presets_ntcCoeffB(uint8_t preset) {
    float presets_AEM_COEFF_B = 2.279654266e-04;
    float presets_BOSCH_COEFF_B = 2.37e-04;
    float presets_GM_COEFF_B = 2.35e-04;
    if (preset == 0) {
        return presets_AEM_COEFF_B;
    }
    if (preset == 1) {
        return presets_BOSCH_COEFF_B;
    }
    if (preset == 2) {
        return presets_GM_COEFF_B;
    }
    return 0.0;
}

float presets_ntcCoeffC(uint8_t preset) {
    float presets_AEM_COEFF_C = 1.197578033e-07;
    float presets_BOSCH_COEFF_C = 9.90e-08;
    float presets_GM_COEFF_C = 9.00e-08;
    if (preset == 0) {
        return presets_AEM_COEFF_C;
    }
    if (preset == 1) {
        return presets_BOSCH_COEFF_C;
    }
    if (preset == 2) {
        return presets_GM_COEFF_C;
    }
    return 0.0;
}

float presets_ntcResistor(uint8_t preset) {
    float presets_AEM_RESISTOR = 10050.0;
    float presets_BOSCH_RESISTOR = 2490.0;
    float presets_GM_RESISTOR = 3000.0;
    if (preset == 0) {
        return presets_AEM_RESISTOR;
    }
    if (preset == 1) {
        return presets_BOSCH_RESISTOR;
    }
    if (preset == 2) {
        return presets_GM_RESISTOR;
    }
    return 0.0;
}

bool presets_isValidNtcPreset(uint8_t preset) {
    return preset <= 2;
}

uint16_t presets_barPresetValue(uint8_t preset) {
    if (preset == 0) {
        return 100;
    }
    if (preset == 1) {
        return 150;
    }
    if (preset == 2) {
        return 200;
    }
    if (preset == 3) {
        return 250;
    }
    if (preset == 4) {
        return 300;
    }
    if (preset == 5) {
        return 400;
    }
    if (preset == 6) {
        return 500;
    }
    if (preset == 7) {
        return 700;
    }
    if (preset == 8) {
        return 1000;
    }
    if (preset == 9) {
        return 5000;
    }
    if (preset == 10) {
        return 10000;
    }
    if (preset == 11) {
        return 15000;
    }
    if (preset == 12) {
        return 20000;
    }
    if (preset == 13) {
        return 21000;
    }
    if (preset == 14) {
        return 22000;
    }
    if (preset == 15) {
        return 23000;
    }
    return 0;
}

uint16_t presets_psiPresetValue(uint8_t preset) {
    if (preset < 20) {
        return 0;
    }
    if (preset > 30) {
        return 0;
    }
    uint8_t idx = preset - 20;
    if (idx == 0) {
        return 15;
    }
    if (idx == 1) {
        return 30;
    }
    if (idx == 2) {
        return 50;
    }
    if (idx == 3) {
        return 100;
    }
    if (idx == 4) {
        return 150;
    }
    if (idx == 5) {
        return 200;
    }
    if (idx == 6) {
        return 250;
    }
    if (idx == 7) {
        return 300;
    }
    if (idx == 8) {
        return 350;
    }
    if (idx == 9) {
        return 400;
    }
    if (idx == 10) {
        return 500;
    }
    return 0;
}

bool presets_isBarPreset(uint8_t preset) {
    return preset <= 15;
}

bool presets_isPsiPreset(uint8_t preset) {
    if (preset < 20) {
        return false;
    }
    if (preset > 30) {
        return false;
    }
    return true;
}

bool presets_isValidPressurePreset(uint8_t preset) {
    bool isBar = presets_isBarPreset(preset);
    if (isBar) {
        return true;
    }
    bool isPsi = presets_isPsiPreset(preset);
    return isPsi;
}
