#ifndef PRESETS_H
#define PRESETS_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
float presets_ntcCoeffA(uint8_t preset);
float presets_ntcCoeffB(uint8_t preset);
float presets_ntcCoeffC(uint8_t preset);
float presets_ntcResistor(uint8_t preset);
bool presets_isValidNtcPreset(uint8_t preset);
uint16_t presets_barPresetValue(uint8_t preset);
uint16_t presets_psiPresetValue(uint8_t preset);
bool presets_isBarPreset(uint8_t preset);
bool presets_isPsiPreset(uint8_t preset);
bool presets_isValidPressurePreset(uint8_t preset);
bool presets_isValidTcType(uint8_t tcType);
uint8_t presets_defaultTcType(void);

#ifdef __cplusplus
}
#endif

#endif /* PRESETS_H */
