/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "sensor_convert.h"

// Sensor Conversion Functions
// Physics calculations for NTC thermistors and pressure sensors
#include <math.h>
#include "AppConfig.h"

#include <stdint.h>

/* Scope: sensor_convert */

float sensor_convert_clampPositive(float x) {
    if (x < 0.0) {
        return 0.0;
    }
    return x;
}

float sensor_convert_defaultAtmosphericPressure(void) {
    float sensor_convert_STANDARD_ATMOSPHERE_KPA = 101.325;
    return sensor_convert_STANDARD_ATMOSPHERE_KPA;
}

float sensor_convert_ntcTemperature(float voltage, const TTempInputConfig* cfg) {
    float sensor_convert_VREF = 5.0;
    if (voltage <= 0.0) {
        return -273.15;
    }
    if (voltage >= sensor_convert_VREF) {
        return -273.15;
    }
    float r_ntc = cfg->resistorValue * voltage / (sensor_convert_VREF - voltage);
    float lnR = log(r_ntc);
    float lnR3 = lnR * lnR * lnR;
    float invT = cfg->coeffA + cfg->coeffB * lnR + cfg->coeffC * lnR3;
    float tempK = 1.0 / invT;
    return tempK - 273.15;
}

float sensor_convert_pressure(float voltage, const TPressureInputConfig* cfg, float atmosphericPressurekPa) {
    float sensor_convert_PSI_TO_KPA = 6.894757;
    float sensor_convert_BAR_TO_KPA = 100.0;
    float sensor_convert_PRESSURE_VOLTAGE_MIN = 0.5;
    float sensor_convert_PRESSURE_VOLTAGE_MAX = 4.5;
    if (voltage < sensor_convert_PRESSURE_VOLTAGE_MIN) {
        return 0.0;
    }
    float clampedVoltage = voltage;
    if (clampedVoltage > sensor_convert_PRESSURE_VOLTAGE_MAX) {
        clampedVoltage = sensor_convert_PRESSURE_VOLTAGE_MAX;
    }
    float ratio = (clampedVoltage - sensor_convert_PRESSURE_VOLTAGE_MIN) / (sensor_convert_PRESSURE_VOLTAGE_MAX - sensor_convert_PRESSURE_VOLTAGE_MIN);
    if (cfg->pressureType == PRESSURE_TYPE_PSIA) {
        if (cfg->maxPressure > 20000) {
            float maxBar = (float)(cfg->maxPressure - 20000);
            float bar = ratio * maxBar;
            return sensor_convert_clampPositive(bar * sensor_convert_BAR_TO_KPA);
        } else {
            float maxkPa = (float)cfg->maxPressure;
            return sensor_convert_clampPositive(ratio * maxkPa);
        }
    } else {
        float maxPsi = (float)cfg->maxPressure;
        float psi = ratio * maxPsi;
        float gaugekPa = psi * sensor_convert_PSI_TO_KPA;
        return sensor_convert_clampPositive(gaugekPa + atmosphericPressurekPa);
    }
}
