/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "spn_category.h"

#include <stdint.h>
#include <stdbool.h>

// SPN Category Lookup Functions
// Maps SPNs to their sensor category (temperature, pressure, EGT, BME280)
// Also provides hi-res SPN mapping for dual-resolution sensors
// Category constants matching ESpnCategory enum values
const uint8_t CAT_UNKNOWN = 0;

const uint8_t CAT_TEMPERATURE = 1;

const uint8_t CAT_PRESSURE = 2;

const uint8_t CAT_EGT = 3;

const uint8_t CAT_BME280 = 4;

/* Scope: spn_category */

uint8_t spn_category_getCategory(uint16_t spn) {
    if (spn == 175) {
        return CAT_TEMPERATURE;
    }
    if (spn == 110) {
        return CAT_TEMPERATURE;
    }
    if (spn == 174) {
        return CAT_TEMPERATURE;
    }
    if (spn == 105) {
        return CAT_TEMPERATURE;
    }
    if (spn == 1131) {
        return CAT_TEMPERATURE;
    }
    if (spn == 1132) {
        return CAT_TEMPERATURE;
    }
    if (spn == 1133) {
        return CAT_TEMPERATURE;
    }
    if (spn == 172) {
        return CAT_TEMPERATURE;
    }
    if (spn == 441) {
        return CAT_TEMPERATURE;
    }
    if (spn == 100) {
        return CAT_PRESSURE;
    }
    if (spn == 109) {
        return CAT_PRESSURE;
    }
    if (spn == 94) {
        return CAT_PRESSURE;
    }
    if (spn == 102) {
        return CAT_PRESSURE;
    }
    if (spn == 106) {
        return CAT_PRESSURE;
    }
    if (spn == 1127) {
        return CAT_PRESSURE;
    }
    if (spn == 1128) {
        return CAT_PRESSURE;
    }
    if (spn == 173) {
        return CAT_EGT;
    }
    if (spn == 171) {
        return CAT_BME280;
    }
    if (spn == 108) {
        return CAT_BME280;
    }
    if (spn == 354) {
        return CAT_BME280;
    }
    return CAT_UNKNOWN;
}

bool spn_category_isValidSpn(uint16_t spn) {
    uint8_t cat = spn_category_getCategory(spn);
    if (cat == CAT_UNKNOWN) {
        return false;
    }
    return true;
}

uint16_t spn_category_getHiResSpn(uint16_t spn) {
    if (spn == 110) {
        return 1637;
    }
    if (spn == 105) {
        return 1363;
    }
    return 0;
}

bool spn_category_hasHiResVariant(uint16_t spn) {
    uint16_t hiRes = spn_category_getHiResSpn(spn);
    if (hiRes == 0) {
        return false;
    }
    return true;
}

bool spn_category_isTemperatureCategory(uint8_t category) {
    if (category == CAT_TEMPERATURE) {
        return true;
    }
    return false;
}

bool spn_category_isPressureCategory(uint8_t category) {
    if (category == CAT_PRESSURE) {
        return true;
    }
    return false;
}
