#ifndef SPN_CHECK_H
#define SPN_CHECK_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
struct AppConfig;

/* Function prototypes */
bool spn_check_isTempSpnEnabled(const AppConfig* cfg, uint16_t spn);
bool spn_check_isPressureSpnEnabled(const AppConfig* cfg, uint16_t spn);
bool spn_check_isSpnEnabled(const AppConfig* cfg, uint16_t spn);

#ifdef __cplusplus
}
#endif

#endif /* SPN_CHECK_H */
