#ifndef SPN_CATEGORY_H
#define SPN_CATEGORY_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t CAT_UNKNOWN;
extern const uint8_t CAT_TEMPERATURE;
extern const uint8_t CAT_PRESSURE;
extern const uint8_t CAT_EGT;
extern const uint8_t CAT_BME280;

/* Function prototypes */
uint8_t spn_category_getCategory(uint16_t spn);
bool spn_category_isValidSpn(uint16_t spn);
uint16_t spn_category_getHiResSpn(uint16_t spn);
bool spn_category_hasHiResVariant(uint16_t spn);
bool spn_category_isTemperatureCategory(uint8_t category);
bool spn_category_isPressureCategory(uint8_t category);

#ifdef __cplusplus
}
#endif

#endif /* SPN_CATEGORY_H */
