#ifndef MAX31856MANAGER_H
#define MAX31856MANAGER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;
typedef struct Adafruit_MAX31856 Adafruit_MAX31856;

/* External variables */
extern const uint8_t thermoCoupleCs;
extern Adafruit_MAX31856 thermocouple;

/* Function prototypes */
void MAX31856Manager_initialize(const AppConfig* config);
bool MAX31856Manager_update(void);
float MAX31856Manager_getTemperatureC(void);
float MAX31856Manager_getColdJunctionC(void);
bool MAX31856Manager_isEnabled(void);
uint8_t MAX31856Manager_getFaultStatus(void);

#ifdef __cplusplus
}
#endif

#endif /* MAX31856MANAGER_H */
