#ifndef APPDATA_H
#define APPDATA_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct AppData {
    float humidity;
    float ambientTemperatureC;
    float absoluteBarometricpressurekPa;
    float oilTemperatureC;
    float oilPressurekPa;
    float coolantTemperatureC;
    float coolantPressurekPa;
    float transferPipeTemperatureC;
    float transferPipePressurekPa;
    float boostPressurekPa;
    float boostTemperatureC;
    float cacInletPressurekPa;
    float cacInletTemperatureC;
    float airInletPressurekPa;
    float airInletTemperatureC;
    float fuelPressurekPa;
    float fuelTemperatureC;
    float engineBayTemperatureC;
    float egtTemperatureC;
} AppData;

#ifdef __cplusplus
}
#endif

#endif /* APPDATA_H */
