#ifndef CRC32_H
#define CRC32_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../AppConfig.hpp"
#include <AppConfig.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t Crc32_calculateChecksum(const AppConfig& config);

#ifdef __cplusplus
}
#endif

#endif /* CRC32_H */
