#ifndef FAULTDECODE_H
#define FAULTDECODE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t FaultDecode_FAULT_OPEN;
extern const uint8_t FaultDecode_FAULT_OVUV;
extern const uint8_t FaultDecode_FAULT_TC_LOW;
extern const uint8_t FaultDecode_FAULT_TC_HIGH;
extern const uint8_t FaultDecode_FAULT_CJ_LOW;
extern const uint8_t FaultDecode_FAULT_CJ_HIGH;
extern const uint8_t FaultDecode_FAULT_TC_RANGE;
extern const uint8_t FaultDecode_FAULT_CJ_RANGE;
extern const uint8_t FaultDecode_IDX_OPEN;
extern const uint8_t FaultDecode_IDX_OVUV;
extern const uint8_t FaultDecode_IDX_TC_LOW;
extern const uint8_t FaultDecode_IDX_TC_HIGH;
extern const uint8_t FaultDecode_IDX_CJ_LOW;
extern const uint8_t FaultDecode_IDX_CJ_HIGH;
extern const uint8_t FaultDecode_IDX_TC_RANGE;
extern const uint8_t FaultDecode_IDX_CJ_RANGE;

/* Function prototypes */
bool FaultDecode_hasFault(uint8_t faultCode);
bool FaultDecode_isOpen(uint8_t faultCode);
bool FaultDecode_isOvuv(uint8_t faultCode);
bool FaultDecode_isTcLow(uint8_t faultCode);
bool FaultDecode_isTcHigh(uint8_t faultCode);
bool FaultDecode_isCjLow(uint8_t faultCode);
bool FaultDecode_isCjHigh(uint8_t faultCode);
bool FaultDecode_isTcRange(uint8_t faultCode);
bool FaultDecode_isCjRange(uint8_t faultCode);
uint8_t FaultDecode_getFirstFaultIndex(uint8_t faultCode);
uint8_t FaultDecode_countFaults(uint8_t faultCode);
bool FaultDecode_isCritical(uint8_t faultCode);

#ifdef __cplusplus
}
#endif

#endif /* FAULTDECODE_H */
