#ifndef FLOATBYTES_H
#define FLOATBYTES_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
float FloatBytes_fromBytesLE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3);
float FloatBytes_fromBytesBE(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3);
uint8_t FloatBytes_getByte0(float value);
uint8_t FloatBytes_getByte1(float value);
uint8_t FloatBytes_getByte2(float value);
uint8_t FloatBytes_getByte3(float value);
bool FloatBytes_isValidFloat(float value);

#ifdef __cplusplus
}
#endif

#endif /* FLOATBYTES_H */
