#ifndef INPUTVALID_H
#define INPUTVALID_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t InputValid_TEMP_COUNT;
extern const uint8_t InputValid_PRESSURE_COUNT;
extern const uint8_t InputValid_NTC_PARAM_COUNT;

/* Function prototypes */
bool InputValid_isValidTempInput(uint8_t input);
bool InputValid_isValidTempIndex(uint8_t index);
uint8_t InputValid_tempInputToIndex(uint8_t input);
uint8_t InputValid_tempIndexToInput(uint8_t index);
bool InputValid_isValidPressureInput(uint8_t input);
bool InputValid_isValidPressureIndex(uint8_t index);
uint8_t InputValid_pressureInputToIndex(uint8_t input);
uint8_t InputValid_pressureIndexToInput(uint8_t index);
bool InputValid_isValidNtcParam(uint8_t param);
bool InputValid_isValidQueryType(uint8_t queryType);
bool InputValid_isValidSubQuery(uint8_t subQuery);
bool InputValid_isValidJ1939Address(uint8_t address);
bool InputValid_isValidAdsDevice(uint8_t device);
bool InputValid_isValidAdsChannel(uint8_t channel);

#ifdef __cplusplus
}
#endif

#endif /* INPUTVALID_H */
