#ifndef J1939BUS_H
#define J1939BUS_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include <Domain/CommandHandler.h>
#include "J1939Encode.h"
#include "FloatBytes.h"
#include <Data/J1939Config.h>
#include <Data/SensorValues.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void J1939Bus_sendPgnGeneric(uint16_t pgn);
void J1939Bus_processConfigCommand(const uint8_t data[8], uint8_t len);
void J1939Bus_initialize(void);

#ifdef __cplusplus
}
#endif

#endif /* J1939BUS_H */
