#ifndef J1939BUS_H
#define J1939BUS_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>
#include "J1939Encode.h"
#include <Data/J1939Config.h>
#include <Data/SensorValues.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void J1939Bus_sendMessage(uint16_t pgn, const uint8_t buf[8]);
void J1939Bus_sendPgnGeneric(uint16_t pgn);
bool J1939Bus_hasPendingCommand(void);
void J1939Bus_getPendingCommand(uint8_t outData[8]);
void J1939Bus_initialize(void);

#ifdef __cplusplus
}
#endif

#endif /* J1939BUS_H */
