#ifndef J1939ENCODE_H
#define J1939ENCODE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint16_t J1939Encode_encode(float value, float resolution, float offset);
uint16_t J1939Encode_temp16bit(float temperatureC);
uint8_t J1939Encode_temp8bit(float temperatureC);
uint8_t J1939Encode_humidity(float humidityPercent);
uint16_t J1939Encode_boost16bit(float pressurekPa);
uint8_t J1939Encode_pressure4kPa(float pressurekPa);
uint8_t J1939Encode_pressure2kPa(float pressurekPa);
uint16_t J1939Encode_pressure16bit(float pressurekPa);
uint8_t J1939Encode_barometric(float pressurekPa);
uint8_t J1939Encode_lowByte(uint16_t value);
uint8_t J1939Encode_highByte(uint16_t value);

#ifdef __cplusplus
}
#endif

#endif /* J1939ENCODE_H */
