#ifndef PRESETS_H
#define PRESETS_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
float Presets_ntcCoeffA(uint8_t preset);
float Presets_ntcCoeffB(uint8_t preset);
float Presets_ntcCoeffC(uint8_t preset);
float Presets_ntcResistor(uint8_t preset);
bool Presets_isValidNtcPreset(uint8_t preset);
uint16_t Presets_barPresetValue(uint8_t preset);
uint16_t Presets_psiPresetValue(uint8_t preset);
bool Presets_isBarPreset(uint8_t preset);
bool Presets_isPsiPreset(uint8_t preset);
bool Presets_isValidPressurePreset(uint8_t preset);
bool Presets_isValidTcType(uint8_t tcType);
uint8_t Presets_defaultTcType(void);

#ifdef __cplusplus
}
#endif

#endif /* PRESETS_H */
