#ifndef SENSORCONVERT_H
#define SENSORCONVERT_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../AppConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct TTempInputConfig TTempInputConfig;
typedef struct TPressureInputConfig TPressureInputConfig;

/* Function prototypes */
float SensorConvert_clampPositive(float x);
float SensorConvert_defaultAtmosphericPressure(void);
float SensorConvert_ntcTemperature(float voltage, const TTempInputConfig& cfg);
float SensorConvert_pressure(float voltage, const TPressureInputConfig& cfg, float atmosphericPressurekPa);

#ifdef __cplusplus
}
#endif

#endif /* SENSORCONVERT_H */
