#ifndef SPNCHECK_H
#define SPNCHECK_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../AppConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct AppConfig AppConfig;

/* Function prototypes */
bool SpnCheck_isTempSpnEnabled(const AppConfig& cfg, uint16_t spn);
bool SpnCheck_isPressureSpnEnabled(const AppConfig& cfg, uint16_t spn);
bool SpnCheck_isSpnEnabled(const AppConfig& cfg, uint16_t spn);

#ifdef __cplusplus
}
#endif

#endif /* SPNCHECK_H */
