#ifndef SPNCATEGORY_H
#define SPNCATEGORY_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
ESpnCategory SpnCategory_getCategory(uint16_t spn);
bool SpnCategory_isValidSpn(uint16_t spn);
uint16_t SpnCategory_getHiResSpn(uint16_t spn);
bool SpnCategory_hasHiResVariant(uint16_t spn);
bool SpnCategory_isTemperatureCategory(ESpnCategory category);
bool SpnCategory_isPressureCategory(ESpnCategory category);

#ifdef __cplusplus
}
#endif

#endif /* SPNCATEGORY_H */
