#ifndef VALUENAME_H
#define VALUENAME_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <Data/types/EValueId.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TValueInfo {
    EValueId id;
    char name[25];
} TValueInfo;

/* External variables */
extern const TValueInfo VALUE_NAMES[EValueId_VALUE_ID_COUNT];

/* Function prototypes */
void ValueName_print(EValueId id);

#ifdef __cplusplus
}
#endif

#endif /* VALUENAME_H */
