/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "BME280Manager.h"

// BME280 Ambient Sensor Manager
// Handles temperature, humidity, and barometric pressure readings
#include <Adafruit_BME280.h>
#include <AppConfig.h>
#include <Arduino.h>
#include <Wire.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: BME280Manager */
static Adafruit_BME280 BME280Manager_bme = {};
static uint8_t BME280Manager_i2cAddress = 0x76;
static bool BME280Manager_enabled = false;
static bool BME280Manager_initialized = false;
static float BME280Manager_temperatureC = 0.0;
static float BME280Manager_humidity = 0.0;
static float BME280Manager_pressurekPa = 0.0;
static bool BME280Manager_readingValid = false;
static uint32_t BME280Manager_lastReadTime = 0;

bool BME280Manager_update(void) {
    if (!BME280Manager_enabled || !BME280Manager_initialized) {
        return false;
    }
    uint32_t now = millis();
    if (now - BME280Manager_lastReadTime < 1000) {
        return false;
    }
    BME280Manager_temperatureC = BME280Manager_bme.readTemperature();
    BME280Manager_humidity = BME280Manager_bme.readHumidity();
    BME280Manager_pressurekPa = BME280Manager_bme.readPressure() / 1000.0;
    bool tempNan = isnan(BME280Manager_temperatureC);
    bool humNan = isnan(BME280Manager_humidity);
    bool presNan = isnan(BME280Manager_pressurekPa);
    if (tempNan || humNan || presNan) {
        BME280Manager_readingValid = false;
        return false;
    }
    BME280Manager_readingValid = true;
    BME280Manager_lastReadTime = now;
    return true;
}

void BME280Manager_initialize(const AppConfig* config) {
    BME280Manager_enabled = config->bme280Enabled;
    if (!BME280Manager_enabled) {
        Serial.println("BME280 disabled in config");
        return;
    }
    BME280Manager_i2cAddress = 0x76;
    bool began = BME280Manager_bme.begin(BME280Manager_i2cAddress);
    if (began) {
        BME280Manager_initialized = true;
        BME280Manager_bme.setSampling(3, 1, 1, 1, 0, 5);
        Serial.print("BME280 initialized at 0x");
        Serial.println(BME280Manager_i2cAddress, HEX);
        BME280Manager_update();
    } else {
        BME280Manager_initialized = false;
        Serial.print("BME280 FAILED to initialize at 0x");
        Serial.print(BME280Manager_i2cAddress, HEX);
        Serial.println(" - check wiring");
        Serial.print("  Sensor ID: 0x");
        Serial.println(BME280Manager_bme.sensorID(), HEX);
        Serial.println("  ID 0xFF = bad address or no sensor");
        Serial.println("  ID 0x56-0x58 = BMP280");
        Serial.println("  ID 0x60 = BME280");
        Serial.println("  ID 0x61 = BME680");
    }
}

float BME280Manager_getTemperatureC(void) {
    if (!BME280Manager_readingValid) {
        return -273.15;
    }
    return BME280Manager_temperatureC;
}

float BME280Manager_getHumidity(void) {
    if (!BME280Manager_readingValid) {
        return 0.0;
    }
    return BME280Manager_humidity;
}

float BME280Manager_getPressurekPa(void) {
    if (!BME280Manager_readingValid) {
        return 0.0;
    }
    return BME280Manager_pressurekPa;
}

bool BME280Manager_isEnabled(void) {
    return BME280Manager_enabled && BME280Manager_initialized;
}
