/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "ConfigStorage.h"

// config_storage.cnx - EEPROM configuration persistence
// Manages loading, saving, and validating AppConfig in EEPROM
#include <Arduino.h>
#include <AppConfig.h>
#include <EEPROM.h>
#include <Display/Crc32.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: ConfigStorage */

bool ConfigStorage_validateConfig(const AppConfig& config) {
    if (config.magic != CONFIG_MAGIC) {
        return false;
    }
    if (config.version != CONFIG_VERSION) {
        return false;
    }
    uint32_t calculatedChecksum = Crc32_calculateChecksum(config);
    if (calculatedChecksum != config.checksum) {
        return false;
    }
    return true;
}

void ConfigStorage_loadDefaults(AppConfig& config) {
    config.magic = CONFIG_MAGIC;
    config.version = CONFIG_VERSION;
    config.j1939SourceAddress = 149;
    for (uint32_t i = 0; i < TEMP_INPUT_COUNT; i += 1) {
        config.tempInputs[i].assignedValue = EValueId_VALUE_UNASSIGNED;
        config.tempInputs[i].coeffA = AEM_TEMP_COEFF_A;
        config.tempInputs[i].coeffB = AEM_TEMP_COEFF_B;
        config.tempInputs[i].coeffC = AEM_TEMP_COEFF_C;
        config.tempInputs[i].resistorValue = AEM_TEMP_RESISTOR;
    }
    for (uint32_t i = 0; i < PRESSURE_INPUT_COUNT; i += 1) {
        config.pressureInputs[i].assignedValue = EValueId_VALUE_UNASSIGNED;
        config.pressureInputs[i].maxPressure = 100;
        config.pressureInputs[i].pressureType = EPressureType_PRESSURE_TYPE_PSIG;
        config.pressureInputs[i].reserved = 0;
    }
    config.egtEnabled = false;
    config.thermocoupleType = EThermocoupleType_TC_TYPE_K;
    config.bme280Enabled = false;
    config.checksum = Crc32_calculateChecksum(config);
}

bool ConfigStorage_saveConfig(const AppConfig& config) {
    AppConfig configToSave = config;
    configToSave.checksum = Crc32_calculateChecksum(config);
    EEPROM.put(0, configToSave);
    return true;
}

void ConfigStorage_loadConfig(AppConfig& config) {
    EEPROM.get(0, config);
    bool isValid = ConfigStorage_validateConfig(config);
    if (!isValid) {
        Serial.println("Loading default configuration");
        ConfigStorage_loadDefaults(config);
        ConfigStorage_saveConfig(config);
    } else {
        Serial.println("Configuration loaded from EEPROM");
    }
}
