/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "MAX31856Manager.h"

// MAX31856 Thermocouple Manager
// Handles EGT (Exhaust Gas Temperature) readings via SPI
#include <Adafruit_MAX31856.h>
#include "AppConfig.h"
#include <Arduino.h>
#include <SPI.h>

#include <stdint.h>
#include <stdbool.h>

// Pin configuration - must be const for C++ constructor
const uint8_t thermoCoupleCs = 10;

// MAX31856 instance with CS pin (file-level for constructor syntax)
Adafruit_MAX31856 thermocouple(thermoCoupleCs);

/* Scope: MAX31856Manager */
static bool MAX31856Manager_enabled = false;
static bool MAX31856Manager_initialized = false;
static bool MAX31856Manager_conversionStarted = false;
static uint32_t MAX31856Manager_conversionStartTime = 0;
static float MAX31856Manager_temperatureC = 0.0;
static float MAX31856Manager_coldJunctionC = 0.0;
static uint8_t MAX31856Manager_faultCode = 0;
static bool MAX31856Manager_readingValid = false;

static void MAX31856Manager_startConversion(void) {
    if (!MAX31856Manager_enabled || !MAX31856Manager_initialized) {
        MAX31856Manager_conversionStarted = false;
        return;
    }
    thermocouple.triggerOneShot();
    MAX31856Manager_conversionStarted = true;
    MAX31856Manager_conversionStartTime = millis();
}

static bool MAX31856Manager_isConversionComplete(void) {
    if (!MAX31856Manager_conversionStarted || !MAX31856Manager_enabled || !MAX31856Manager_initialized) {
        return false;
    }
    int32_t drdyState = digitalRead(2);
    if (drdyState == LOW) {
        return true;
    }
    return thermocouple.conversionComplete();
}

static void MAX31856Manager_readResult(void) {
    if (!MAX31856Manager_enabled || !MAX31856Manager_initialized) {
        return;
    }
    MAX31856Manager_faultCode = thermocouple.readFault();
    if (MAX31856Manager_faultCode != 0) {
        MAX31856Manager_readingValid = false;
    } else {
        MAX31856Manager_temperatureC = thermocouple.readThermocoupleTemperature();
        MAX31856Manager_coldJunctionC = thermocouple.readCJTemperature();
        MAX31856Manager_readingValid = true;
    }
    MAX31856Manager_conversionStarted = false;
}

void MAX31856Manager_initialize(const AppConfig* config) {
    MAX31856Manager_enabled = config->egtEnabled;
    if (!MAX31856Manager_enabled) {
        Serial.println("MAX31856 disabled in config");
        return;
    }
    pinMode(2, INPUT);
    pinMode(3, INPUT);
    bool began = thermocouple.begin();
    if (began) {
        MAX31856Manager_initialized = true;
        thermocouple.setThermocoupleType(static_cast<uint8_t>(config->thermocoupleType));
        thermocouple.setNoiseFilter(0);
        thermocouple.setConversionMode(0);
        Serial.println("MAX31856 initialized");
        MAX31856Manager_startConversion();
    } else {
        MAX31856Manager_initialized = false;
        Serial.println("MAX31856 FAILED to initialize");
    }
}

bool MAX31856Manager_update(void) {
    if (!MAX31856Manager_enabled || !MAX31856Manager_initialized) {
        return false;
    }
    if (!MAX31856Manager_conversionStarted) {
        MAX31856Manager_startConversion();
        return false;
    }
    bool complete = MAX31856Manager_isConversionComplete();
    if (complete) {
        MAX31856Manager_readResult();
        MAX31856Manager_startConversion();
        return true;
    }
    uint32_t now = millis();
    if (now - MAX31856Manager_conversionStartTime > 500) {
        MAX31856Manager_readingValid = false;
        MAX31856Manager_conversionStarted = false;
        MAX31856Manager_startConversion();
    }
    return false;
}

float MAX31856Manager_getTemperatureC(void) {
    if (!MAX31856Manager_readingValid) {
        return -273.15;
    }
    return MAX31856Manager_temperatureC;
}

float MAX31856Manager_getColdJunctionC(void) {
    if (!MAX31856Manager_readingValid) {
        return -273.15;
    }
    return MAX31856Manager_coldJunctionC;
}

bool MAX31856Manager_isEnabled(void) {
    return MAX31856Manager_enabled && MAX31856Manager_initialized;
}

uint8_t MAX31856Manager_getFaultStatus(void) {
    return MAX31856Manager_faultCode;
}
