/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "SensorValues.h"

// Centralized sensor value storage
// All values stored in standard units (kPa, °C, %)
#include "types/EValueId.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: SensorValues */
TSensorValue SensorValues_current[EValueId_VALUE_ID_COUNT] = {0};

void SensorValues_initialize(void) {
    for (uint8_t i = 0; i < EValueId_VALUE_ID_COUNT; i = i + 1) {
        SensorValues_current[i].value = 0.0;
        SensorValues_current[i].hasHardware = false;
    }
}
